/* Nội dung dữ liệu cho Bản đồ Face Yoga. Toạ độ SVG theo viewBox 0 0 400 540, vẽ nửa trái (người xem) rồi lật gương. */
window.DATA = {

/* ---------------- CƠ ---------------- */
muscles: [
  { id:"platysma", vn:"Cơ bám da cổ", en:"Platysma", nerve:"TK VII (nhánh cổ)", group:"relax",
    d:"M146,396 L188,424 L182,536 L96,536 Q116,470 146,396 Z",
    act:"Kéo khoé miệng và da cổ xuống; căng lên khi nghiến răng hoặc gồng cổ.",
    issue:"Dải dọc ở cổ, đường hàm kém rõ, nếp ngang cổ (kèm tư thế cúi điện thoại).",
    yoga:"Ngồi thẳng, nhìn chéo lên trần, đẩy môi dưới ra và ép lưỡi lên vòm miệng 5 giây × 8. Giữ cổ dài, không gập cổ ra sau tối đa.",
    warn:"Người thoái hoá đốt sống cổ hoặc chóng mặt khi ngửa: giảm biên độ, tập ngồi có tựa." },
  { id:"trapezius", vn:"Cơ thang (phần trên)", en:"Upper trapezius", nerve:"TK XI", group:"relax",
    d:"M142,432 L152,474 L44,532 L18,524 Q84,474 142,432 Z",
    act:"Nâng vai, giữ đầu; căng mạn tính khi ngồi máy tính, bế con, stress.",
    issue:"Căng cổ vai gáy, đau đầu căng cơ, vai nhô, đầu đưa ra trước. Gián tiếp làm mặt “nặng” và kém dẫn lưu.",
    yoga:"Lăn vai chậm 8 lần; nghiêng tai về vai, thở ra dài 5 nhịp mỗi bên; kết thúc bằng tư thế cá có gối đỡ hoặc tư thế em bé có bolster.",
    warn:"Huyệt Kiên tỉnh (GB21) trên đỉnh vai: theo truyền thống tránh ấn mạnh ở phụ nữ mang thai." },
  { id:"scm", vn:"Cơ ức đòn chũm", en:"Sternocleidomastoid", nerve:"TK XI", group:"relax",
    d:"M104,288 L120,286 L194,522 L176,524 Z",
    act:"Xoay, gập, nghiêng cổ; tham gia thở ngực khi thở gấp.",
    issue:"Căng khi đầu đưa ra trước và khi thở ngực. Dọc theo cơ là chuỗi hạch cổ và tĩnh mạch cảnh, nên cơ căng có thể đi kèm cảm giác mặt phù.",
    yoga:"Xoay đầu 45° rồi ngẩng nhẹ cằm để kéo giãn, 5 nhịp thở. Véo nhẹ và lăn dọc thân cơ bằng ngón cái và ngón trỏ, từ sau tai xuống xương đòn.",
    warn:"Không ấn sâu vào hõm cổ phía trước (động mạch cảnh). Chỉ thao tác trên da và thân cơ." },
  { id:"digastric", vn:"Cơ hai bụng và nhóm trên móng", en:"Digastric / suprahyoids", nerve:"TK V3 và VII", group:"tone",
    d:"M164,420 Q184,442 200,446 L200,454 Q178,452 156,428 Z",
    act:"Hạ hàm, nâng xương móng, hỗ trợ nuốt.",
    issue:"Vùng dưới cằm chảy, góc cổ–cằm kém rõ. Nghiên cứu 2025 ghi nhận cơ này có hiệu ứng thay đổi lớn nhất sau 8 tuần face yoga; nghiên cứu 2018 thấy thiết diện cơ tăng.",
    yoga:"Gập cằm kháng lực: đặt nắm tay dưới cằm, ép cằm xuống vào tay 5 giây × 10. Ép cả mặt lưỡi lên vòm miệng rồi nuốt chậm × 5.",
    warn:"Đau khớp thái dương hàm: dùng lực rất nhẹ.", ev:["guzel","hwang"] },
  { id:"frontalis", vn:"Cơ trán", en:"Frontalis", nerve:"TK VII (nhánh thái dương)", group:"relax",
    d:"M124,150 C128,100 160,66 196,62 L196,160 C176,156 150,156 128,162 Z",
    act:"Nhướn mày, kéo da trán lên. Là cơ duy nhất nâng được lông mày.",
    issue:"Nếp nhăn ngang trán. Hay hoạt động quá mức ở người sụp mí (nhướn bù trừ) và người hay “cười bằng trán”.",
    yoga:"Đặt hai bàn tay ngang trán giữ da phẳng, mở to mắt nhìn lên mà không để trán nhăn, 10 giây × 3. Vuốt từ giữa trán ra thái dương.",
    warn:"Bài nhướn mày lặp nhiều lần có thể làm nếp ngang sâu thêm. Với cơ này, nên tập thả lỏng thay vì tăng cường." },
  { id:"temporalis", vn:"Cơ thái dương", en:"Temporalis", nerve:"TK V3", group:"relax",
    d:"M100,140 C104,118 124,112 134,128 L128,196 L108,226 Q98,190 100,140 Z",
    act:"Nâng và kéo lùi hàm dưới; co khi nghiến răng.",
    issue:"Đau đầu vùng thái dương do căng cơ, nghiến răng đêm, căng thẳng.",
    yoga:"Đặt đầu ngón tay lên thái dương, há miệng nhẹ, xoay tròn chậm 10 vòng mỗi chiều kèm thở ra dài. Huyệt Thái dương nằm ở vùng này.",
    warn:"Đau đầu đột ngột, dữ dội, “chưa từng có” thì không phải việc của lớp yoga: cần gọi cấp cứu." },
  { id:"masseter", vn:"Cơ cắn", en:"Masseter", nerve:"TK V3", group:"relax",
    d:"M108,252 L142,254 L150,350 L128,352 Q114,320 108,252 Z",
    act:"Nâng hàm, nhai, nghiến. Tính theo lực trên diện tích, đây là một trong những cơ khoẻ nhất cơ thể.",
    issue:"Phì đại cơ làm hàm vuông; nghiến răng, đau khớp thái dương hàm, mặt “gồng” khi stress.",
    yoga:"Tư thế nghỉ hàm: lưỡi chạm vòm ngay sau răng cửa, môi khép, răng tách nhau. Day cơ cắn bằng khớp ngón tay theo vòng nhỏ. Tư thế sư tử (Simhasana) để xả căng. Huyệt Giáp xa (ST6) và Hạ quan (ST7).",
    warn:"Kẹt hàm, há miệng lệch, tiếng lục cục kèm đau: chuyển nha sĩ hoặc bác sĩ răng hàm mặt." },
  { id:"buccinator", vn:"Cơ mút (cơ thổi kèn)", en:"Buccinator", nerve:"TK VII", group:"tone",
    d:"M120,300 Q140,290 166,312 Q166,330 162,336 Q138,336 122,326 Z",
    act:"Ép má vào răng khi nhai, thổi, mút.",
    issue:"Má hóp hoặc chảy. Nghiên cứu Myoton 2025: trương lực và độ cứng cơ mút tăng sau 8 tuần tập.",
    yoga:"“Mặt cá”: hóp má rồi cố mỉm cười, 5 giây × 8. Hoặc ngậm hơi, đẩy hơi qua lại hai bên má 30 giây.",
    warn:"Massage trong khoang miệng (buccal) chỉ làm khi đã học kỹ thuật và vệ sinh (găng tay, cắt móng).", ev:["guzel"] },
  { id:"orbicularis_oculi", vn:"Cơ vòng mắt", en:"Orbicularis oculi", nerve:"TK VII", group:"balance",
    d:"M126,200 A36,26 0 1,0 198,200 A36,26 0 1,0 126,200 Z M139,200 A23,12 0 1,1 185,200 A23,12 0 1,1 139,200 Z",
    act:"Nhắm, nheo, chớp mắt. Phần ổ mắt tham gia nụ cười thật (Duchenne).",
    issue:"Vết chân chim do phần ngoài co nhiều; mí dưới chùng và bọng mắt do phần mi yếu, kèm ứ dịch.",
    yoga:"Bài chữ V: ngón giữa đặt ở đầu mày, ngón trỏ ở đuôi mày, nhìn lên trần và nheo mí dưới lên, giữ 5 giây × 6. Thả lỏng đuôi mắt bằng cách ấn nhẹ, không kéo da.",
    warn:"Da quanh mắt mỏng nhất trên mặt. Dùng ngón áp út, không chà, không kéo." },
  { id:"corrugator", vn:"Cơ cau mày", en:"Corrugator supercilii", nerve:"TK VII", group:"relax",
    d:"M166,168 Q178,160 192,166 Q180,174 166,168 Z",
    act:"Kéo đầu mày xuống và vào trong khi cau mày, tập trung, chói nắng.",
    issue:"Nếp dọc giữa hai mày (“số 11”). Nghiên cứu Myoton 2025: trương lực giảm sau 8 tuần tập.",
    yoga:"Day vòng nhỏ ở đầu mày (huyệt Toản trúc BL2) rồi vuốt dọc lông mày ra ngoài khi thở ra. Tập nhận biết lúc mình đang cau mày trước màn hình.",
    warn:"Cau mày nhiều khi đọc có thể do mắt cần kính. Gợi ý học viên đi khám mắt.", ev:["guzel"] },
  { id:"procerus", vn:"Cơ tháp mũi (cơ mảnh khảnh)", en:"Procerus", nerve:"TK VII", group:"relax", mid:true,
    d:"M193,168 L207,168 L205,200 L195,200 Z",
    act:"Kéo da giữa hai mày xuống.",
    issue:"Nếp ngang ở gốc mũi.",
    yoga:"Đặt hai ngón trỏ ở gốc mũi, vuốt thẳng lên trán qua huyệt Ấn đường 10 lần khi thở ra dài.",
    warn:"" },
  { id:"nasalis", vn:"Cơ mũi", en:"Nasalis", nerve:"TK VII", group:"balance",
    d:"M191,236 Q183,254 186,272 L195,266 Q193,250 197,234 Z",
    act:"Nở hoặc khép lỗ mũi.",
    issue:"Ít ảnh hưởng thẩm mỹ. Hữu ích để dạy học viên nhận biết thở mũi.",
    yoga:"Thở mũi chậm, chú ý cảm giác cánh mũi nở khi hít vào. Ghép với pranayama (thở bụng, Nadi Shodhana).",
    warn:"" },
  { id:"llsan", vn:"Cơ nâng môi trên và cánh mũi", en:"Levator labii superioris alaeque nasi", nerve:"TK VII", group:"balance",
    d:"M191,212 L185,212 L177,318 L185,320 Z",
    act:"Nâng môi trên, nở cánh mũi (động tác “nhăn mũi”).",
    issue:"Liên quan phần trên của rãnh mũi má.",
    yoga:"Nhăn mũi thật chậm, có kiểm soát, rồi thả 6 lần. Vuốt rãnh mũi má từ cánh mũi chéo lên gò má.",
    warn:"" },
  { id:"lls", vn:"Cơ nâng môi trên", en:"Levator labii superioris", nerve:"TK VII", group:"tone",
    d:"M150,226 L168,224 L182,320 L173,322 Z",
    act:"Nâng môi trên; góp phần tạo độ đầy vùng má giữa.",
    issue:"Má giữa xẹp, rãnh mũi má rõ hơn khi lão hoá.",
    yoga:"Nâng má: miệng chữ O, môi trên phủ kín răng, mỉm cười để nâng gò má, đầu ngón tay đặt nhẹ trên gò má để cảm nhận, 5 giây × 10.",
    warn:"" },
  { id:"zyg_minor", vn:"Cơ gò má bé", en:"Zygomaticus minor", nerve:"TK VII", group:"tone",
    d:"M132,236 L144,230 L177,320 L170,323 Z",
    act:"Nâng môi trên ra ngoài, tham gia nụ cười.",
    issue:"Độ đầy má trên. Nghiên cứu Northwestern 2018 ghi nhận má trên và má dưới đầy hơn rõ rệt sau 20 tuần.",
    yoga:"Kết hợp với bài nâng má. Giữ ở mức co vừa phải, không cười căng hết cỡ.",
    warn:"", ev:["alam"] },
  { id:"zyg_major", vn:"Cơ gò má lớn", en:"Zygomaticus major", nerve:"TK VII", group:"tone",
    d:"M112,248 L126,238 L172,328 L164,334 Z",
    act:"Kéo khoé miệng lên và ra ngoài: cơ chính của nụ cười.",
    issue:"Khoé miệng chùng, mặt trông mệt. Hwang 2018: thiết diện cơ tăng sau 8 tuần tập có dụng cụ.",
    yoga:"Mỉm cười ngậm môi, nâng khoé miệng thật chậm về phía đuôi mắt, giữ 10 giây, thả chậm × 6.",
    warn:"", ev:["hwang"] },
  { id:"lao", vn:"Cơ nâng góc miệng", en:"Levator anguli oris", nerve:"TK VII", group:"tone",
    d:"M162,262 L171,260 L171,326 L165,328 Z",
    act:"Nâng góc miệng thẳng lên. Nằm sâu dưới cơ nâng môi trên.",
    issue:"Khoé miệng trễ.",
    yoga:"Đặt ngón trỏ ở khoé miệng tạo lực cản nhẹ, nâng khoé lên chống lại ngón tay, 5 giây × 8.",
    warn:"" },
  { id:"risorius", vn:"Cơ cười ngang", en:"Risorius", nerve:"TK VII", group:"balance",
    d:"M120,322 L165,328 L165,336 L120,342 Z",
    act:"Kéo khoé miệng sang ngang.",
    issue:"Cười căng ngang lâu dài có thể tạo nếp ở má dưới. Đây là cơ có nhiều biến thể giải phẫu, một số người không có.",
    yoga:"Không cần tập riêng. Hướng dẫn học viên cười “lên” (về phía đuôi mắt) thay vì “ngang”.",
    warn:"" },
  { id:"orbicularis_oris", vn:"Cơ vòng môi", en:"Orbicularis oris", nerve:"TK VII", group:"balance", mid:true,
    d:"M158,331 A42,22 0 1,0 242,331 A42,22 0 1,0 158,331 Z M170,331 A30,9 0 1,1 230,331 A30,9 0 1,1 170,331 Z",
    act:"Khép, chu, mím môi; phát âm.",
    issue:"Nếp nhăn dọc quanh môi, nặng hơn khi hút thuốc, dùng ống hút nhiều. Nghiên cứu Myoton 2025: trương lực giảm, độ đàn hồi tăng.",
    yoga:"Chu môi rồi cười rộng, luân phiên 10 lần. Ép hai môi vào nhau 5 giây rồi thả.",
    warn:"Herpes môi đang bùng phát: không thao tác vùng môi.", ev:["guzel"] },
  { id:"dao", vn:"Cơ hạ góc miệng", en:"Depressor anguli oris", nerve:"TK VII", group:"relax",
    d:"M164,340 L172,342 L184,404 L148,398 Z",
    act:"Kéo khoé miệng xuống (vẻ buồn, chê).",
    issue:"Rãnh từ khoé miệng xuống cằm (rãnh marionette), mặt trông buồn.",
    yoga:"Day xoắn nhẹ từ khoé miệng xuống bờ hàm. Sau đó tập nâng khoé (cơ nâng góc miệng) để cân bằng.",
    warn:"" },
  { id:"dli", vn:"Cơ hạ môi dưới", en:"Depressor labii inferioris", nerve:"TK VII", group:"balance",
    d:"M176,350 L192,352 L196,404 L185,405 Z",
    act:"Kéo môi dưới xuống và ra ngoài.",
    issue:"Ít khi cần tập riêng.",
    yoga:"Đi kèm bài cổ: đẩy môi dưới ra khi nhìn chéo lên.",
    warn:"" },
  { id:"mentalis", vn:"Cơ cằm", en:"Mentalis", nerve:"TK VII", group:"relax",
    d:"M186,372 Q194,370 197,380 L196,404 Q186,400 184,388 Z",
    act:"Nhăn da cằm, đẩy môi dưới lên.",
    issue:"Cằm sần “vỏ cam” khi khép môi. Thường gặp ở người thở miệng hoặc khớp cắn hở.",
    yoga:"Day tròn cằm 20 giây. Nhắc học viên khép môi nhẹ, không gồng cằm.",
    warn:"Cằm luôn gồng khi khép môi: gợi ý khám nha khoa hoặc tai mũi họng (thở miệng, khớp cắn)." }
],

/* ---------------- BẠCH HUYẾT ---------------- */
nodes: [
  { id:"pre", vn:"Hạch trước tai (mang tai)", en:"Preauricular / parotid", x:110, y:238,
    from:"Trán, thái dương, mí mắt phần ngoài, má trên.", to:"Hạch cổ sâu.",
    how:"Đặt hai ngón trỏ và giữa thành chữ V ôm quanh tai. Làm vòng tròn tĩnh tại thật nhẹ 5–10 lần rồi vuốt xuống cổ." },
  { id:"retro", vn:"Hạch sau tai (chũm)", en:"Retroauricular / mastoid", x:95, y:292,
    from:"Da đầu vùng đỉnh và thái dương sau, mặt sau vành tai.", to:"Hạch cổ nông và cổ sâu.",
    how:"Cùng thao tác chữ V với hạch trước tai." },
  { id:"buccal", vn:"Hạch má (cơ mút)", en:"Buccal / facial", x:148, y:302,
    from:"Mũi, má, môi trên.", to:"Hạch dưới hàm.",
    how:"Lòng ngón tay phẳng, kéo da rất nhẹ từ cánh mũi ngang ra góc hàm." },
  { id:"mand", vn:"Hạch hàm dưới", en:"Mandibular", x:146, y:368,
    from:"Má dưới, môi.", to:"Hạch dưới hàm.",
    how:"Đi kèm thao tác dọc bờ hàm." },
  { id:"subm", vn:"Hạch dưới hàm", en:"Submandibular", x:158, y:410,
    from:"Má, mũi, môi trên, phần ngoài môi dưới, lợi, góc mắt trong (qua hạch mặt).", to:"Hạch cổ sâu.",
    how:"Từ giữa cằm vuốt dọc dưới xương hàm ra góc hàm, rồi xuống cổ." },
  { id:"subment", vn:"Hạch dưới cằm", en:"Submental", x:200, y:438, mid:true,
    from:"Giữa môi dưới, cằm, đầu lưỡi, sàn miệng.", to:"Hạch dưới hàm và hạch cổ sâu.",
    how:"Ngón tay đặt dưới cằm, kéo da nhẹ ra hai bên về phía góc hàm." },
  { id:"cerv_sup", vn:"Hạch cổ nông", en:"Superficial cervical", x:128, y:462,
    from:"Vùng sau tai, tuyến mang tai, da cổ.", to:"Hạch cổ sâu.",
    how:"Lòng bàn tay phẳng, vuốt từ dưới tai xuống xương đòn." },
  { id:"cerv_deep", vn:"Hạch cổ sâu (chuỗi cảnh trong)", en:"Deep cervical", x:164, y:470,
    from:"Gần như toàn bộ đầu, mặt, cổ. Mọi nhóm hạch phía trên đều đổ về đây.", to:"Thân bạch huyết cảnh, rồi về hội lưu tĩnh mạch.",
    how:"Vuốt dọc cổ bên (theo cơ ức đòn chũm) từ trên xuống, rất nhẹ." },
  { id:"supra", vn:"Hạch thượng đòn (terminus)", en:"Supraclavicular / venous angle", x:142, y:512,
    from:"Toàn bộ dòng bạch huyết đầu cổ trước khi đổ vào máu.", to:"Hội lưu tĩnh mạch cảnh trong và dưới đòn. Bên trái qua ống ngực, bên phải qua ống bạch huyết phải.",
    how:"Bước đầu tiên và cuối cùng của mọi buổi dẫn lưu. Đặt ngón tay phẳng vào hõm trên xương đòn, kéo da nhẹ vào trong và xuống 10 lần." }
],
flows: [
  "M150,108 Q116,160 110,226", "M134,206 Q120,220 113,232", "M182,270 Q160,290 150,300 Q148,360 156,400",
  "M172,332 Q160,370 158,400", "M198,404 L199,428", "M110,250 Q122,360 160,458", "M96,300 Q110,380 128,452",
  "M160,418 L163,458", "M163,480 Q156,500 146,508"
],
mld: [
  { t:"Thở bụng", n:[], d:"5 nhịp: hít vào bụng phồng, thở ra dài gấp đôi. Thay đổi áp lực ngực–bụng hỗ trợ dòng chảy trong ống ngực, nơi bạch huyết đổ về tĩnh mạch." },
  { t:"Mở “cửa” thượng đòn", n:["supra"], d:"Ngón tay phẳng đặt vào hõm trên xương đòn, kéo da rất nhẹ vào trong và xuống, 10 lần. Phải làm sạch “cửa xả” trước khi đẩy dịch từ mặt về." },
  { t:"Cổ bên", n:["cerv_deep","cerv_sup"], d:"Lòng bàn tay phẳng, vuốt từ dưới dái tai xuống dọc cổ tới xương đòn, 10 lần mỗi bên." },
  { t:"Quanh tai", n:["pre","retro"], d:"Ngón trỏ và giữa xoè chữ V ôm quanh tai, vòng tròn tĩnh tại 5–10 lần, rồi vuốt xuống cổ." },
  { t:"Dưới cằm → dưới hàm", n:["subment","subm"], d:"Từ giữa cằm vuốt dọc mặt dưới xương hàm ra góc hàm, nối tiếp xuống cổ." },
  { t:"Má và cánh mũi", n:["buccal","mand","subm"], d:"Từ cánh mũi kéo da ngang qua má về góc hàm và trước tai. Ba đường: cánh mũi, gò má, khoé miệng." },
  { t:"Quanh mắt", n:["pre"], d:"Ngón áp út rất nhẹ, từ khoé mắt trong theo bờ ổ mắt dưới ra đuôi mắt, qua thái dương về trước tai. Không kéo da." },
  { t:"Trán và kết thúc", n:["pre","cerv_deep","supra"], d:"Từ giữa trán vuốt ra thái dương, xuống trước tai, dọc cổ về thượng đòn. Kết thúc bằng 3 nhịp ở hõm thượng đòn." }
],

/* ---------------- HUYỆT KINH ĐIỂN ---------------- */
points: [
  { id:"yintang", vn:"Ấn đường", code:"EX-HN3 / GV29", x:200, y:182, mid:true, loc:"Chính giữa hai đầu lông mày.", use:"An thần, đau đầu vùng trán, nghẹt mũi. Thư giãn nếp cau mày.", warn:"" },
  { id:"gb14", vn:"Dương bạch", code:"GB14", x:160, y:140, loc:"Trên điểm giữa lông mày 1 thốn.", use:"Đau đầu vùng trán, nếp nhăn trán (ứng dụng làm đẹp).", warn:"" },
  { id:"bl2", vn:"Toản trúc", code:"BL2", x:187, y:171, loc:"Chỗ lõm ở đầu trong lông mày.", use:"Mỏi mắt, đau đầu, cau mày.", warn:"" },
  { id:"yuyao", vn:"Ngư yêu", code:"EX-HN4", x:160, y:166, loc:"Giữa lông mày, thẳng trên con ngươi.", use:"Mỏi mắt, nặng mí.", warn:"" },
  { id:"te23", vn:"Ty trúc không", code:"TE23", x:134, y:175, loc:"Chỗ lõm ở đuôi lông mày.", use:"Đau đầu bên, giật mí.", warn:"" },
  { id:"taiyang", vn:"Thái dương", code:"EX-HN5", x:118, y:192, loc:"Hõm thái dương, giữa đuôi mày và đuôi mắt lùi ra sau khoảng 1 thốn.", use:"Đau đầu, mỏi mắt, căng cơ thái dương.", warn:"" },
  { id:"gb1", vn:"Đồng tử liêu", code:"GB1", x:131, y:203, loc:"Ngoài khoé mắt ngoài khoảng 0,5 thốn.", use:"Mỏi mắt; vùng vết chân chim.", warn:"" },
  { id:"bl1", vn:"Tình minh", code:"BL1", x:186, y:198, loc:"Hơi trên khoé mắt trong.", use:"Mỏi mắt.", warn:"Rất gần nhãn cầu: chỉ ấn cực nhẹ, không day mạnh. Trong châm cứu đây là huyệt cần kỹ thuật cao." },
  { id:"st1", vn:"Thừa khấp", code:"ST1", x:162, y:217, loc:"Thẳng dưới con ngươi, giữa nhãn cầu và bờ dưới ổ mắt.", use:"Bọng mắt (kết hợp dẫn lưu), mỏi mắt.", warn:"Ấn trên bờ xương, không ấn vào nhãn cầu." },
  { id:"st2", vn:"Tứ bạch", code:"ST2", x:162, y:232, loc:"Chỗ lõm của lỗ dưới ổ mắt.", use:"Da mặt, mắt, đau mặt.", warn:"" },
  { id:"si18", vn:"Quyền liêu", code:"SI18", x:134, y:260, loc:"Bờ dưới xương gò má, thẳng dưới đuôi mắt.", use:"Đau mặt, co giật mặt; dùng nhiều trong các bài nâng cơ.", warn:"" },
  { id:"st3", vn:"Cự liêu", code:"ST3", x:163, y:276, loc:"Thẳng dưới con ngươi, ngang bờ dưới cánh mũi.", use:"Đau mặt; vùng má giữa.", warn:"" },
  { id:"li20", vn:"Nghênh hương", code:"LI20", x:180, y:281, loc:"Cạnh trung điểm cánh mũi, trong rãnh mũi má.", use:"Nghẹt mũi; vùng rãnh mũi má.", warn:"" },
  { id:"st7", vn:"Hạ quan", code:"ST7", x:113, y:252, loc:"Hõm trước tai, dưới cung gò má (sờ khi ngậm miệng).", use:"Khớp thái dương hàm, đau răng, căng hàm.", warn:"" },
  { id:"gv26", vn:"Nhân trung (Thuỷ câu)", code:"GV26", x:200, y:306, mid:true, loc:"Điểm 1/3 trên của rãnh nhân trung.", use:"Truyền thống dùng để hồi tỉnh khi ngất.", warn:"Người ngất thật cần gọi cấp cứu 115 trước." },
  { id:"st4", vn:"Địa thương", code:"ST4", x:170, y:334, loc:"Ngoài khoé miệng khoảng 0,4 thốn.", use:"Vùng khoé miệng và rãnh cười.", warn:"" },
  { id:"st6", vn:"Giáp xa", code:"ST6", x:132, y:338, loc:"Trên góc hàm khoảng một khoát ngón tay, chỗ cơ cắn nổi lên khi cắn chặt.", use:"Nghiến răng, căng hàm, đau răng.", warn:"" },
  { id:"cv24", vn:"Thừa tương", code:"CV24", x:200, y:372, mid:true, loc:"Chỗ lõm giữa rãnh cằm–môi.", use:"Vùng cằm, tiết nước bọt.", warn:"" },
  { id:"te17", vn:"Ế phong", code:"TE17", x:100, y:296, loc:"Sau dái tai, trong hõm giữa xương chũm và góc hàm.", use:"Ù tai, đau mặt.", warn:"Vùng có thần kinh mặt đi ra: ấn nhẹ." },
  { id:"st12", vn:"Khuyết bồn", code:"ST12", x:150, y:510, loc:"Giữa hố trên xương đòn.", use:"Truyền thống dùng cho ho, đau họng. Trùng với vùng “terminus” của hệ bạch huyết.", warn:"Ấn nông, không ấn sâu." }
],

/* ---------------- LINH KHU 49 – NGŨ SẮC ---------------- */
zones: [
  { id:"z_ting", han:"庭", vn:"Đình (giữa trán trên)", org:"Đầu, mặt", x:200, y:96, mid:true, src:"庭者，首面也" },
  { id:"z_qs", han:"闕上", vn:"Khuyết thượng (trên ấn đường)", org:"Yết hầu (họng)", x:200, y:148, mid:true, src:"闕上者，咽喉也" },
  { id:"z_qz", han:"闕中", vn:"Khuyết trung (giữa hai mày)", org:"Phế", x:200, y:180, mid:true, src:"闕中者，肺也" },
  { id:"z_xj", han:"下極", vn:"Hạ cực (gốc mũi, giữa hai mắt)", org:"Tâm", x:200, y:205, mid:true, src:"下極者，心也" },
  { id:"z_zx", han:"直下", vn:"Trực hạ (sống mũi)", org:"Can", x:200, y:238, mid:true, src:"直下者，肝也" },
  { id:"z_gz", han:"肝左", vn:"Cạnh vùng Can", org:"Đởm", x:189, y:232, src:"肝左者，膽也" },
  { id:"z_mw", han:"下者 (面王)", vn:"Đầu mũi (Diện vương)", org:"Tỳ", x:200, y:276, mid:true, src:"下者，脾也" },
  { id:"z_fs", han:"方上", vn:"Cánh mũi", org:"Vị", x:184, y:285, src:"方上者，胃也" },
  { id:"z_xc", han:"面王以上", vn:"Hai bên trên đầu mũi", org:"Tiểu trường", x:187, y:262, src:"面王以上者，小腸也" },
  { id:"z_zy", han:"中央", vn:"Giữa má", org:"Đại trường", x:152, y:282, src:"中央者，大腸也" },
  { id:"z_jd", han:"挾大腸", vn:"Má ngoài (kẹp vùng Đại trường)", org:"Thận", x:128, y:288, src:"挾大腸者，腎也" },
  { id:"z_qi", han:"當腎者", vn:"Dưới vùng Thận", org:"Rốn", x:132, y:312, src:"當腎者，臍也" },
  { id:"z_rz", han:"面王以下", vn:"Nhân trung (dưới đầu mũi)", org:"Bàng quang, tử xứ (tử cung)", x:200, y:304, mid:true, src:"面王以下者，膀胱子處也" },
  { id:"z_qu", han:"顴", vn:"Gò má", org:"Vai", x:132, y:242, src:"顴者，肩也" },
  { id:"z_qh", han:"顴後", vn:"Sau gò má", org:"Cánh tay", x:112, y:262, src:"顴後者，臂也" },
  { id:"z_bx", han:"臂下", vn:"Dưới vùng cánh tay", org:"Bàn tay", x:114, y:290, src:"臂下者，手也" },
  { id:"z_mn", han:"目內眥上", vn:"Trên khoé mắt trong", org:"Ngực, vú", x:182, y:190, src:"目內眥上者，膺乳也" },
  { id:"z_js", han:"挾繩而上", vn:"Phía ngoài má, sát tai", org:"Lưng", x:106, y:214, src:"挾繩而上者，背也" },
  { id:"z_gu", han:"循牙車以下", vn:"Từ góc hàm đi xuống", org:"Đùi", x:126, y:334, src:"循牙車以下者，股也" },
  { id:"z_xi", han:"中央", vn:"Giữa bờ hàm", org:"Gối", x:140, y:372, src:"中央者，膝也" },
  { id:"z_jing", han:"膝以下", vn:"Dưới vùng gối", org:"Cẳng chân", x:156, y:396, src:"膝以下者，脛也" },
  { id:"z_zu", han:"當脛以下", vn:"Dưới vùng cẳng chân", org:"Bàn chân", x:172, y:414, src:"當脛以下者，足也" }
],

/* ---------------- DÒNG THỜI GIAN ---------------- */
timeline: [
  { y:"~TK 2 TCN – TK 1", tag:"dongy", t:"Hoàng Đế Nội Kinh", d:"Linh Khu thiên 49 “Ngũ sắc” vẽ cả cơ thể lên khuôn mặt (gò má ứng với vai, sống mũi ứng với Can...). Thiên 4 viết: mười hai kinh mạch, ba trăm sáu mươi lăm lạc, khí huyết đều lên mặt.", s:["lk49","lk4"] },
  { y:"TK 15", tag:"yoga", t:"Simhasana trong Hatha Yoga Pradipika", d:"Tư thế sư tử (há miệng, thè lưỡi, mở to mắt) được mô tả trong chương 1. Đây là bài “face yoga” cổ điển nhất còn được dạy đến nay.", s:["hyp"] },
  { y:"1472", tag:"chau-a", t:"Kobido, Nhật Bản", d:"Theo truyền thuyết, hai bậc thầy Anma thi nhau tìm kỹ thuật massage mặt tinh tế nhất. Phái thắng cuộc lập nên Kobido, với hơn 40 kỹ thuật tay, ban đầu dành cho hoàng tộc.", s:["kobido"] },
  { y:"1932", tag:"tay", t:"Dẫn lưu bạch huyết Vodder", d:"Emil và Estrid Vodder phát triển kỹ thuật dẫn lưu bạch huyết thủ công ở Cannes cho bệnh nhân sưng hạch cổ mạn tính.", s:["vodder"] },
  { y:"1970s–80s", tag:"tay", t:"Tập cơ mặt lên báo Mỹ", d:"Các bài báo về “thể dục cho khuôn mặt” xuất hiện. Nguồn gốc chính xác của face yoga hiện đại vẫn chưa rõ ràng.", s:["ctv"] },
  { y:"26/3/1980", tag:"vn", t:"Diện chẩn Bùi Quốc Châu", d:"Ông Bùi Quốc Châu tìm ra huyệt đầu tiên. Trong khoảng 3 năm, nhóm của ông xác định thêm hàng trăm huyệt và các đồ hình phản chiếu cơ thể trên mặt.", s:["lc_dc"] },
  { y:"1988", tag:"tay", t:"Facial Reflexology (Sorensensistem)", d:"Lone Sorensen (Đan Mạch) kết hợp Diện chẩn với truyền thống Nam Mỹ và giải phẫu học thành phương pháp phản xạ mặt.", s:["sorensen"] },
  { y:"1995", tag:"tay", t:"Facercise", d:"Carole Maggio xuất bản sách Facercise, đưa “tập thể hình cho mặt” ra đại chúng ở Mỹ.", s:[] },
  { y:"2006", tag:"chau-a", t:"Face Yoga Method", d:"Fumiko Takatsu (Nhật) bắt đầu hệ thống bài tập sau một tai nạn xe năm 35 tuổi làm lệch cơ thể và khuôn mặt. Về sau chương trình mở đào tạo giáo viên.", s:["takatsu"] },
  { y:"2007", tag:"yoga", t:"The Yoga Face", d:"Annelise Hagen, giáo viên yoga ở New York, xuất bản sách. Bà định vị face yoga là lựa chọn không xâm lấn thay cho Botox và filler.", s:["hagen","nbc"] },
  { y:"2014", tag:"khoahoc", t:"Tổng quan hệ thống đầu tiên", d:"Van Borsel và cộng sự tìm được 9 nghiên cứu, đều ở Nam Mỹ. Tất cả báo cáo kết quả tốt nhưng chất lượng chưa đủ để kết luận.", s:["vanborsel"] },
  { y:"2018", tag:"khoahoc", t:"Northwestern / JAMA Dermatology", d:"16 phụ nữ 40–65 tuổi tập 30 phút mỗi ngày trong 20 tuần. Tuổi ước tính giảm từ 50,8 xuống 48,1; má trên và má dưới đầy hơn.", s:["alam","sd2018"] },
  { y:"2021–22", tag:"vn", t:"Face yoga vào studio Việt Nam", d:"Ally Vân Anh và Lenka Seminova nhận chứng chỉ Face Yoga Method năm 2021, mở workshop 1,5 giờ ở Sài Gòn. Khoá online của Nguyễn Hiếu trên Unica vượt 18.000 học viên.", s:["athas","unica"] },
  { y:"2024–25", tag:"chau-a", t:"“Slow aging” ở Hàn Quốc", d:"Olive Young báo doanh số nhóm sản phẩm “slow aging” tăng hơn 60% năm 2024. Làm đẹp chuyển dần sang lối sống: ngủ, stress, vận động.", s:["oliveyoung"] },
  { y:"2025", tag:"khoahoc", t:"Đo cơ bằng Myoton", d:"Nghiên cứu 8 tuần trên 12 phụ nữ: cơ nông (trán, cau mày, vòng mắt, vòng môi) giảm trương lực; cơ mút và cơ hai bụng tăng; mọi cơ đều đàn hồi hơn.", s:["guzel"] }
],

/* ---------------- NGÁCH ---------------- */
niches: [
  { t:"Face yoga + cổ vai gáy cho dân văn phòng", fit:5, demand:"Cao", ev:"Vừa", tags:["offline","online","b2b"],
    d:"Ghép bài cổ vai gáy, tư thế đầu và mắt màn hình với face yoga. Đây là ngách gần nhất với chuyên môn yoga phục hồi, dễ bán cho doanh nghiệp." },
  { t:"Thư giãn hàm, nghiến răng, khớp thái dương hàm", fit:5, demand:"Trung bình", ev:"Vừa", tags:["offline","refer"],
    d:"Tư thế nghỉ hàm, thở, thả lỏng cơ cắn và cơ thái dương. Nên có kênh giới thiệu hai chiều với nha sĩ." },
  { t:"Tiền mãn kinh và mãn kinh", fit:4, demand:"Cao", ev:"Vừa", tags:["offline","online"],
    d:"Da mỏng và khô nhanh trong giai đoạn này, kèm bốc hoả và mất ngủ. Gói face yoga, thở làm dịu, ngủ và chăm sóc da cơ bản." },
  { t:"Sau sinh", fit:4, demand:"Trung bình", ev:"Yếu", tags:["offline","online"],
    d:"Cổ vai gáy do bế và cho con bú, mặt phù, thiếu ngủ. Buổi ngắn 15–20 phút, tập ở tư thế ngồi." },
  { t:"Dẫn lưu bạch huyết mặt và gua sha", fit:4, demand:"Cao", ev:"Yếu", tags:["offline","product"],
    d:"Dễ “thấy ngay” (giảm bọng buổi sáng), hợp nội dung video. Cần học kỹ thuật tay và vệ sinh dụng cụ." },
  { t:"Yoga mắt và mỏi mắt màn hình", fit:4, demand:"Trung bình", ev:"Vừa", tags:["online","b2b"],
    d:"Quy tắc 20-20-20, chớp mắt chủ động, thả lỏng cơ vòng mắt. Hợp làm mini-class cho doanh nghiệp." },
  { t:"Thử thách online 21–28 ngày", fit:4, demand:"Cao", ev:"—", tags:["online"],
    d:"Mô hình đã chạy tốt ở Việt Nam (Unica, Udemy). Cần ảnh chụp chuẩn hoá trước–sau và cộng đồng nhắc tập." },
  { t:"Chương trình cho doanh nghiệp", fit:4, demand:"Trung bình", ev:"—", tags:["b2b"],
    d:"Gói 6–8 buổi “giải toả căng thẳng khuôn mặt và cổ” cho nhân viên văn phòng, ngân hàng, call center." },
  { t:"Người cao tuổi: biểu cảm, nuốt, phát âm", fit:3, demand:"Đang lên", ev:"Vừa", tags:["offline","refer"],
    d:"Theo mô hình Brazil, nơi chuyên viên âm ngữ trị liệu dùng bài tập cơ mặt trong chăm sóc ban đầu. Phải phối hợp với chuyên viên y tế." },
  { t:"Nam giới: đường hàm, căng thẳng", fit:3, demand:"Đang lên", ev:"Yếu", tags:["online"],
    d:"Ngôn ngữ “tập luyện” thay vì “làm đẹp”: hàm, cổ, tư thế, giấc ngủ." },
  { t:"Kobido và massage mặt thủ công", fit:3, demand:"Cao", ev:"Yếu", tags:["offline","spa"],
    d:"Hợp tác với spa. Cần học tay nghề bài bản, đầu tư thời gian thực hành nhiều nhất trong các ngách." },
  { t:"Đào tạo giáo viên face yoga", fit:3, demand:"Trung bình", ev:"—", tags:["online","offline"],
    d:"Thị trường còn ít người có chứng chỉ quốc tế. Nên làm sau khi đã dạy ổn định 1–2 năm." },
  { t:"Sản phẩm: dầu, đá gua sha, thiết bị", fit:2, demand:"Cao", ev:"Yếu", tags:["product"],
    d:"Biên lợi nhuận tốt nhưng dễ trượt sang quảng cáo quá đà. Thiết bị vi dòng, LED đang là xu hướng." },
  { t:"Đồng hành sau thẩm mỹ", fit:2, demand:"Trung bình", ev:"Yếu", tags:["refer","spa"],
    d:"Hướng dẫn khi nào tập lại sau tiêm botox, filler, căng chỉ. Bắt buộc theo chỉ định của bác sĩ." }
],

/* ---------------- SO SÁNH QUỐC GIA ---------------- */
countries: [
  { c:"Nhật Bản", phil:"Tối giản, phòng ngừa. Mục tiêu da “mochi” mềm căng; coi trọng chống nắng và làm sáng da (bihaku).",
    ritual:"4–6 bước: tẩy trang dầu và sữa rửa mặt, lotion dưỡng ẩm vỗ nhiều lớp mỏng, tinh chất, kem, chống nắng.",
    ingr:"Cám gạo, men lên men, trà xanh, dầu hoa trà (tsubaki), tảo biển.",
    hand:"Kobido (từ 1472), Shiatsu, con lăn mặt, tập cơ biểu cảm (表情筋トレ).",
    trend:"Tập cơ mặt do chuyên gia lớn tuổi dẫn dắt; mặt nạ và dụng cụ tập cơ.",
    lesson:"Nhịp chậm, nghi thức hoá, kỹ thuật tay chuẩn hoá đến từng động tác.", s:["sokoglam","kobido","jp63"] },
  { c:"Hàn Quốc", phil:"Cấp ẩm nhiều lớp, “glass skin”. Từ 2024 chuyển sang “slow aging” (phòng ngừa sớm, lối sống) và “skip-care” (cắt bớt bước).",
    ritual:"Có thể tới 10 bước: dầu, sữa rửa, tẩy tế bào chết, toner, essence, serum/ampoule, mặt nạ giấy, kem mắt, kem dưỡng, chống nắng.",
    ingr:"Rau má (cica), nhân sâm (hanbang, Đông y Hàn), dịch ốc sên, ngải cứu, thành phần lên men.",
    hand:"Thiết bị tại nhà (vi dòng, RF, LED), massage dẫn lưu, da liễu thẩm mỹ rất phổ biến.",
    trend:"Olive Young: nhóm sản phẩm slow aging tăng hơn 60% năm 2024.",
    lesson:"Đặt face yoga trong câu chuyện lối sống “slow aging” (ngủ, stress, vận động) thay vì “chống già”.", s:["sokoglam","oliveyoung","skipcare"] },
  { c:"Trung Quốc", phil:"Đông y: vẻ đẹp phản ánh khí huyết và tạng phủ. Dưỡng sinh từ trong ra ngoài; vọng chẩn khuôn mặt.",
    ritual:"Thực dưỡng và trà thảo mộc bên trong, mặt nạ thảo dược bên ngoài.",
    ingr:"Bột trân châu, nhân sâm, bạch chỉ (gây cảm quang), đương quy, cam thảo, hoa cúc, câu kỷ.",
    hand:"Quát sa (gua sha), con lăn ngọc, giác hơi mặt, châm cứu thẩm mỹ, Tui Na.",
    trend:"Gua sha và con lăn ngọc toàn cầu hoá qua mạng xã hội.",
    lesson:"Kể chuyện kinh lạc hấp dẫn, nhưng phải nói rõ mức bằng chứng.", s:["lk49","guasha"] },
  { c:"Việt Nam", phil:"Đan xen Đông y, kinh nghiệm dân gian và ảnh hưởng mạnh của K-beauty. Chuộng da sáng, sản phẩm “thiên nhiên”.",
    ritual:"Dân gian: nước vo gạo, nghệ với mật ong, xông lá (sả, bưởi, ngải). Hiện đại: routine kiểu Hàn.",
    ingr:"Rau má, nghệ, gạo, trà xanh, lô hội, bồ kết (tóc).",
    hand:"Diện chẩn (1980), bấm huyệt dưỡng sinh, cạo gió, gội đầu dưỡng sinh.",
    trend:"Cơ sở thẩm mỹ tăng từ khoảng 100 (2000) lên 5.000 (2020); mỹ phẩm thiên nhiên và hữu cơ ước vượt 62 triệu USD năm 2025.",
    lesson:"Cạo gió và gội đầu dưỡng sinh là thói quen sẵn có, làm cầu nối văn hoá cho face yoga và cổ vai gáy. Cảnh báo học viên về mặt nạ chanh tự chế.", s:["dbnd","lc_dc"] },
  { c:"Ấn Độ", phil:"Ayurveda: cân bằng ba dosha; da phản ánh tiêu hoá (agni).",
    ritual:"Ubtan (bột đậu, nghệ, đàn hương), dầu mặt kumkumadi, Mukha Abhyanga (massage mặt bằng dầu ấm).",
    ingr:"Nghệ, đàn hương, neem, nghệ tây, ghee.",
    hand:"Gậy Kansa (hợp kim đồng), huyệt Marma; Simhasana từ Hatha yoga.",
    trend:"Ayurveda cao cấp xuất khẩu; khoá marma cho giáo viên yoga.",
    lesson:"Cùng gốc với yoga nên dễ ghép với pranayama, dầu ấm và marma trong một buổi.", s:["hyp"] },
  { c:"Thái Lan", phil:"Y học cổ truyền Thái: dùng nhiệt, thảo dược và áp lực.",
    ritual:"Túi chườm thảo dược nóng (luk pra kob), massage mặt Thái, mặt nạ me và nghệ.",
    ingr:"Me, nghệ, sả, gừng, dừa.",
    hand:"Nuad Thai (UNESCO ghi danh di sản phi vật thể năm 2019).",
    trend:"Du lịch wellness, spa nghỉ dưỡng.",
    lesson:"Thêm nhiệt ấm và thảo dược vào phần thư giãn cuối buổi.", s:[] },
  { c:"Pháp", phil:"“Ít mà chất”: da khoẻ, dược mỹ phẩm bán ở hiệu thuốc.",
    ritual:"Làm sạch nhẹ (nước micellar), serum, kem dưỡng.",
    ingr:"Nước khoáng suối nóng, polyphenol nho, tinh dầu.",
    hand:"Véo lăn Jacquet, dẫn lưu bạch huyết Vodder (khởi nguồn ở Cannes, 1932).",
    trend:"Thẩm mỹ “tự nhiên”, không làm quá.",
    lesson:"Chuẩn hoá kỹ thuật dẫn lưu, dùng ngôn ngữ chính xác.", s:["vodder"] },
  { c:"Anh / Mỹ", phil:"Dựa trên bằng chứng: retinoid, chống nắng, hoạt chất. Face fitness thành ngành dịch vụ.",
    ritual:"Tối giản hoạt chất: làm sạch, vitamin C, retinoid, kem dưỡng, chống nắng.",
    ingr:"Retinoid, vitamin C, niacinamide, peptide, ceramide.",
    hand:"Face yoga (Hagen ở New York, Danielle Collins ở Anh), thiết bị vi dòng, LED.",
    trend:"App face yoga, chứng chỉ online, studio “tập gym cho mặt”.",
    lesson:"Học mô hình kinh doanh: app, khoá online, chứng chỉ giáo viên.", s:["hagen","collins","apps"] },
  { c:"Brazil", phil:"Fonoaudiologia estética: chuyên viên âm ngữ trị liệu dùng bài tập cơ mặt cho mục đích thẩm mỹ, có chương trình trong chăm sóc sức khoẻ ban đầu.",
    ritual:"Đánh giá cơ mặt và cổ, rồi bài tập, massage, thư giãn.",
    ingr:"—",
    hand:"Bài tập vận động miệng–mặt (motricidade orofacial).",
    trend:"Cả 9 nghiên cứu trong tổng quan 2014 đều từ Nam Mỹ.",
    lesson:"Mô hình “phục hồi chức năng sang thẩm mỹ” rất gần với giáo viên yoga phục hồi.", s:["brazil","vanborsel"] }
],

/* ---------------- NGUỒN ---------------- */
sources: {
  alam:{ t:"Alam M. và cs. Association of Facial Exercise With the Appearance of Aging. JAMA Dermatology, 2018. Thông cáo của Northwestern University.", u:"https://news.northwestern.edu/stories/2018/january/facial-exercises-help-middle-aged-women-appear-more-youthful" },
  sd2018:{ t:"ScienceDaily (2018). Facial exercises help middle-aged women appear more youthful.", u:"https://www.sciencedaily.com/releases/2018/01/180103160142.htm" },
  vanborsel:{ t:"Van Borsel J. và cs. The effectiveness of facial exercises for facial rejuvenation: a systematic review. Aesthetic Surgery Journal 34(1):22–27, 2014. Tóm tắt trên MedEsthetics.", u:"https://www.medestheticsmag.com/news/article/21145684/benefits-of-facial-exercises-for-aesthetic-rejuvenation-inconclusive" },
  guzel:{ t:"Güzel và cs. Effect of Intensive Face Yoga on Facial Muscles Tonus, Stiffness, and Elasticity in Middle-Aged Women. Medicina (Kaunas), 2025.", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC12112979/" },
  hwang:{ t:"Hwang U.J. và cs. Effect of a Facial Muscle Exercise Device on Facial Rejuvenation. Aesthetic Surgery Journal, 2018.", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC5888959" },
  scielo:{ t:"Facial exercises for rejuvenation: A systematic review. Revista CEFAC (SciELO).", u:"https://www.scielo.br/j/rcefac/a/QJYZ8mZXHD7krKHxGzhsJGz/" },
  nct:{ t:"ClinicalTrials.gov NCT06765408. Effect of Face Yoga on Mimic Muscles.", u:"https://clinicaltrials.gov/study/NCT06765408" },
  hagen:{ t:"Penguin Random House. The Yoga Face – Annelise Hagen (2007).", u:"https://penguinrandomhouse.com/books/300700/the-yoga-face-by-annelise-hagen" },
  nbc:{ t:"NBC News. New Yorkers try facial yoga for natural lift.", u:"https://www.nbcnews.com/news/amp/wbna20610259" },
  takatsu:{ t:"Discover Nikkei (2026). Fumiko Takatsu.", u:"https://discovernikkei.org/en/journal/2026/1/7/fumiko-takatsu/" },
  ctv:{ t:"CTV News. Does face yoga actually work? Experts weigh in.", u:"https://www.ctvnews.ca/health/article/does-face-yoga-actually-work-experts-weigh-in-on-its-slimming-anti-aging-effects/" },
  collins:{ t:"Evolve Beauty. Face Yoga Exercises From Danielle Collins (tiểu sử, các văn bằng).", u:"https://www.evolvebeauty.com/blogs/news/face-yoga-exercises-from-danielle-collins" },
  sikorski:{ t:"AARP. Face Workouts That Work (Gary Sikorski, Happy Face Yoga).", u:"https://www.aarp.org/health/healthy-living/info-2018/facial-exercises-fd.html" },
  gvr:{ t:"Treendly, dẫn số liệu Grand View Research: thị trường face yoga 779,5 triệu USD (2020), 1,02 tỷ USD (2027), CAGR 5,3%.", u:"https://treendly.com/blog/face-yoga-the-emerging-trend-for-natural-anti-aging-and-facial-toning" },
  accio:{ t:"Accio. Face yoga equipment: CAGR 14,1% giai đoạn 2026–2033 (nguồn tổng hợp thương mại).", u:"https://www.accio.com/business/face-yoga-equipment" },
  gwi:{ t:"Global Wellness Institute (2024). The Global Wellness Economy Reaches a New Peak of $6.3 Trillion.", u:"https://globalwellnessinstitute.org/press-room/press-releases/the-global-wellness-economy-reaches-a-new-peak-of-6-3-trillion-and-is-forecast-to-hit-9-trillion-by-2028/" },
  apps:{ t:"ScreensDesign. Guided face yoga apps (ước tính doanh thu và lượt cài trung bình).", u:"https://screensdesign.com/categories/guided-face-yoga-apps/" },
  cosbiz:{ t:"Cosmetics Business. How can beauty brands benefit from the face yoga trend?", u:"https://cosmeticsbusiness.com/how-can-beauty-brands-benefit-from-the-face-yoga-trend--138695" },
  dbnd:{ t:"Báo Đại biểu Nhân dân. Nhận diện và nắm bắt cơ hội tăng trưởng đột phá thị trường làm đẹp tại Việt Nam.", u:"https://daibieunhandan.vn/nhan-dien-va-nam-bat-co-hoi-tang-truong-dot-pha-thi-truong-lam-dep-tai-viet-nam-10335369.html" },
  bcompany:{ t:"B-Company. Vietnam Beauty Market 2025: Key Updates, Investment Activities, and Trends.", u:"https://b-company.jp/vietnam-beauty-market-2025-key-updates-investment-activities-and-trends/" },
  ken:{ t:"Ken Research. Vietnam Fitness Services Market.", u:"https://www.kenresearch.com/industry-reports/vietnam-fitness-services-market.md" },
  cand:{ t:"CAND. 6,000 yoga practitioners to participate in International Yoga Day in Vietnam.", u:"https://en.cand.com.vn/law-society/6-000-yoga-practitioners-to-participate-in-International-Yoga-Day-in-Vietnam-i525467/" },
  plo:{ t:"PLO. Hơn 3.000 thương hiệu ngành làm đẹp quy tụ tại triển lãm ở TP.HCM.", u:"https://plo.vn/hon-3000-thuong-hieu-nganh-lam-dep-dang-quy-tu-tai-trien-lam-o-tphcm-post862101.html" },
  unica:{ t:"Unica. Yoga trẻ hoá và làm đẹp cho khuôn mặt (Nguyễn Hiếu).", u:"https://unica.vn/yoga-tre-hoa-va-lam-dep-cho-khuon-mat" },
  athas:{ t:"Athas Saigon. Yoga khuôn mặt: “Dùng đi, không là mất đó” (workshop 28/5/2022).", u:"https://www.athassaigon.com/events/2022/5/28/yoga-khun-mt-dng-i-khng-l-mt-face-yoga-workshop-use-them-or-lose-them" },
  udemy:{ t:"Udemy. 28 ngày điêu khắc gương mặt rạng ngời cùng yoga face.", u:"https://www.udemy.com/course/yoga-face-coach-trang/" },
  vinmec:{ t:"Vinmec. Các bài tập trên mặt có thực sự giúp bạn trông trẻ hơn?", u:"https://www.vinmec.com/vie/bai-viet/cac-bai-tap-tren-mat-co-thuc-su-giup-ban-trong-tre-hon-vi" },
  lc_fy:{ t:"Nhà thuốc Long Châu. Face yoga: bí quyết cho làn da săn chắc.", u:"https://nhathuoclongchau.com.vn/bai-viet/face-yoga-bi-quyet-cho-lan-da-san-chac-tre-dep.html" },
  ytl:{ t:"Yoga Therapy Vietnam. Đào tạo Yoga Trị liệu 200 giờ.", u:"https://yogatherapy.vn/dao-tao-yoga-tri-lieu/" },
  omf:{ t:"OM Factory Vietnam. Khoá đào tạo giáo viên Yin Yoga.", u:"https://omfactory.vn/khoa-dao-tao-giao-vien-yin-yoga/" },
  ydaily:{ t:"Yogadaily. Khoá đào tạo giáo viên Yoga trị liệu online.", u:"https://yogaonline.yogadaily.com.vn/san-pham/khoa-hoc-huan-luyen-vien-yoga-tri-lieu-v2" },
  lc_dc:{ t:"Nhà thuốc Long Châu. Diện chẩn chữa mất ngủ có hiệu quả không? (lịch sử, ghi chú bằng chứng).", u:"https://nhathuoclongchau.com.vn/bai-viet/dien-chan-chua-mat-ngu-co-hieu-qua-khong.html" },
  eco_dc:{ t:"Ecopharma. Diện chẩn chữa mất ngủ (các bộ huyệt 26; 124–34–0; 1–26–37–50–103–106–267–300).", u:"https://ecopharma.com.vn/dien-chan-chua-mat-ngu/" },
  lc_dc2:{ t:"Nhà thuốc Long Châu. Chữa rối loạn tiêu hoá bằng diện chẩn: công dụng và lưu ý.", u:"https://nhathuoclongchau.com.vn/bai-viet/chua-roi-loan-tieu-hoa-bang-dien-chan-cong-dung-va-nhung-dieu-can-luu-y-54331.html" },
  sggp:{ t:"SGGP (13/4/2012). Phản hồi từ bài viết “Mơ hồ liệu pháp diện chẩn”: Sẽ xử lý việc khám chữa bệnh trái phép.", u:"https://www.sggp.org.vn/phan-hoi-tu-bai-viet-mo-ho-lieu-phap-dien-chan-se-xu-ly-viec-kham-chua-benh-trai-phep-130463.html" },
  sorensen:{ t:"ABMP. Lone Sorensen – Facial Reflexology.", u:"https://learn.abmp.com/node/15401" },
  eminence:{ t:"Eminence Organics. Facial Reflexology (Dien Chan và Sorensensistem).", u:"https://eminenceorganics.com/us/blog/skin-care/facial-reflexology-benefits-reflexology-may-surprise-you.html" },
  lk49:{ t:"Hoàng Đế Nội Kinh – Linh Khu, thiên 49 “Ngũ sắc” (五色). Chinese Text Project.", u:"https://ctext.org/huangdi-neijing/wu-se" },
  lk4:{ t:"Hoàng Đế Nội Kinh – Linh Khu, thiên 4 “Tà khí tạng phủ bệnh hình” (邪氣藏府病形). Chinese Text Project.", u:"https://ctext.org/huangdi-neijing/xie-qi-zang-fu-bing-xing" },
  lk10:{ t:"Hoàng Đế Nội Kinh – Linh Khu, thiên 10 “Kinh mạch” (經脈). Chinese Text Project.", u:"https://ctext.org/huangdi-neijing/jing-mai" },
  sv1:{ t:"Hoàng Đế Nội Kinh – Tố Vấn, thiên 1 “Thượng cổ thiên chân luận” (上古天真論).", u:"https://ctext.org/huangdi-neijing/shang-gu-tian-zhen-lun" },
  sv9:{ t:"Hoàng Đế Nội Kinh – Tố Vấn, thiên 9 “Lục tiết tạng tượng luận” (六節藏象論).", u:"https://ctext.org/huangdi-neijing/liu-jie-zang-xiang-lun" },
  nanjing:{ t:"Nạn Kinh, nạn 61: “Vọng nhi tri chi vị chi thần” (望而知之謂之神).", u:"" },
  hyp:{ t:"Hatha Yoga Pradipika (Svatmarama, TK 15), chương 1, các câu 50–52: Simhasana.", u:"" },
  statpearls:{ t:"StatPearls. Anatomy, Head and Neck, Lymph Nodes.", u:"https://www.statpearls.com/point-of-care/25607" },
  kenhub:{ t:"Kenhub. Facial lymph nodes.", u:"https://www.kenhub.com/en/library/anatomy/facial-lymph-nodes" },
  vodder:{ t:"Wittlinger H. và cs. Dr. Vodder's Manual Lymph Drainage. Thieme.", u:"https://shop.thieme.de/en/Dr.-Vodder-s-Manual-Lymph-Drainage/9783132578746" },
  abmp_mld:{ t:"ABMP. Manual Lymph Drainage (áp lực dưới khoảng 9 ounce/inch², nhịp tròn đều).", u:"https://plove.abmp.com/manual-lymph-drainage" },
  guasha:{ t:"North Biomedical. Gua Sha Benefits for Skin: What the Science Actually Supports (bình luận nghiên cứu Nielsen 2007, EXPLORE).", u:"https://northbiomedical.com/articles/gua-sha-benefits/" },
  kobido:{ t:"Dermascope. Keeping Up with Kobido: History, Benefits, Incorporation.", u:"https://www.dermascope.com/keeping-up-with-kobido-history-benefits-incorporation/" },
  sokoglam:{ t:"Soko Glam – The Klog. Korean vs. Japanese Skin Care.", u:"https://sokoglam.com/blogs/theklog/korean-skin-care-vs-japanese-skin-care" },
  oliveyoung:{ t:"CJ Newsroom. CJ Olive Young reports over 60% annual sales growth in slow-aging products.", u:"https://newsroom.cj.net/cj-olive-young-reports-over-60-annual-sales-growth-in-slow-aging-products" },
  skipcare:{ t:"Yahoo Life. “Skip care” is the new K-beauty trend.", u:"https://ca.news.yahoo.com/skip-care-k-beauty-trend-131721172.html" },
  jp63:{ t:"The Standard (HK). 63-year-old beauty expert's facial muscle training.", u:"https://www.thestandard.com.hk/wellness/article/324944/63-yo-beauty-experts-secret-to-reversing-skin-age-by-10-years-without-surgery" },
  brazil:{ t:"Speech Therapy and Facial Esthetic: Experience of Brazil in Primary Health Care. Revista Chilena de Fonoaudiología.", u:"https://revistaschilenas.uchile.cl/handle/2250/31977?show=full" },
  tcr:{ t:"Frontiers in Neurology 7:221 (2016). Trigeminocardiac reflex và phản xạ lặn.", u:"https://dx.doi.org/10.3389/fneur.2016.00221" },
  coles:{ t:"Coles N.A. và cs. (2019), Psychological Bulletin: phân tích gộp 138 nghiên cứu về phản hồi nét mặt. Tin ScienceDaily.", u:"https://www.sciencedaily.com/releases/2019/04/190412094728.htm" },
  botox:{ t:"Tổng quan: Treatment of Depression with Botulinum Toxin (gồm RCT Wollmer 2012, n=30).", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9231293/" },
  loken:{ t:"Löken L.S. và cs. Coding of pleasant touch by unmyelinated afferents in humans. Nature Neuroscience 12:547–548, 2009.", u:"https://www.nature.com/articles/nn.2312" },
  penfield:{ t:"Penfield W., Boldrey E. Somatic motor and sensory representation in the cerebral cortex of man. Brain, 1937.", u:"" },
  aha:{ t:"American Heart Association. Warning Signs of a Heart Attack (đau lan hàm, cổ, cánh tay).", u:"https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack" },
  myers:{ t:"Myers T. Anatomy Trains (mô hình các đường mạc nối dài; Deep Front Line nối lưỡi, xương móng, cơ hoành, sàn chậu).", u:"" },
  hughes:{ t:"Hughes M.C. và cs. Sunscreen and prevention of skin aging: a randomized trial. Annals of Internal Medicine 158:781–790, 2013.", u:"https://www.acpjournals.org/doi/10.7326/0003-4819-158-11-201306040-00002" },
  aad:{ t:"American Academy of Dermatology. Skin care during menopause (da mất khoảng 30% collagen trong 5 năm đầu mãn kinh).", u:"https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/skin-care-during-menopause" },
  hansraj:{ t:"Hansraj K.K. Assessment of stresses in the cervical spine caused by posture and position of the head. Surgical Technology International 25:277–279, 2014.", u:"" },
  luat:{ t:"Luật Khám bệnh, chữa bệnh số 15/2023/QH15 (hiệu lực từ 01/01/2024).", u:"" }
}
};
