/* Dữ liệu cho Bản đồ Face Yoga.
   Toạ độ theo pixel của ảnh chân dung gốc (864×1184; ảnh nền là phần cắt x 110–760, y 120–940).
   Vẽ nửa trái của hình (bên phải người được vẽ) rồi lật gương quanh trục x = 435, trừ mục có mid:true hoặc single:true. */
window.DATA = {

/* ---------------- CƠ ----------------
   geo.type: band (dải theo đường cong bậc ba, w = độ rộng đầu–cuối), sheet (tấm giữa hai mép a, b),
   ring (vòng elip, o = ngoài, i = trong), fan (quạt hội tụ về apex) */
muscles: [
  { id:"trapezius", vn:"Cơ thang (phần trên)", en:"Upper trapezius", nerve:"TK XI", group:"relax",
    geo:{ type:"band", p:[[322,782],[294,800],[226,832],[156,856]], w:[28,24] },
    act:"Nâng vai, giữ đầu; căng mạn tính khi ngồi máy tính, bế con, stress.",
    issue:"Căng cổ vai gáy, đau đầu căng cơ, đầu đưa ra trước. Gián tiếp làm mặt “nặng” và kém dẫn lưu.",
    yoga:"Lăn vai chậm 8 lần; nghiêng tai về vai, thở ra dài 5 nhịp mỗi bên; kết thúc bằng tư thế cá có gối đỡ.",
    warn:"Huyệt Kiên tỉnh (GB21) trên đỉnh vai: theo truyền thống tránh ấn mạnh ở phụ nữ mang thai." },
  { id:"platysma", vn:"Cơ bám da cổ", en:"Platysma", nerve:"TK VII (nhánh cổ)", group:"relax",
    geo:{ type:"sheet", a:[[322,634],[346,660],[386,684],[422,694]], b:[[232,880],[290,892],[352,902],[402,904]], n:9 },
    act:"Kéo khoé miệng và da cổ xuống; căng lên khi nghiến răng hoặc gồng cổ.",
    issue:"Dải dọc ở cổ, đường hàm kém rõ, nếp ngang cổ khi hay cúi nhìn điện thoại.",
    yoga:"Ngồi thẳng, nhìn chéo lên trần, đẩy môi dưới ra và ép lưỡi lên vòm miệng 5 giây × 8. Giữ cổ dài, không ngửa tối đa.",
    warn:"Thoái hoá đốt sống cổ hoặc chóng mặt khi ngửa: giảm biên độ, tập ngồi có tựa." },
  { id:"scm", vn:"Cơ ức đòn chũm", en:"Sternocleidomastoid", nerve:"TK XI", group:"relax",
    geo:{ type:"band", p:[[318,630],[344,720],[380,820],[416,893]], w:[32,24] },
    act:"Xoay, gập, nghiêng cổ; tham gia thở ngực khi thở gấp.",
    issue:"Căng khi đầu đưa ra trước và khi thở ngực. Chuỗi hạch cổ và tĩnh mạch cảnh nằm dọc theo cơ này.",
    yoga:"Xoay đầu 45° rồi ngẩng nhẹ cằm, giữ 5 nhịp thở. Véo nhẹ và lăn dọc thân cơ từ sau tai xuống xương đòn.",
    warn:"Không ấn sâu vào hõm cổ phía trước (động mạch cảnh)." },
  { id:"digastric", vn:"Cơ hai bụng và nhóm trên móng", en:"Digastric / suprahyoids", nerve:"TK V3 và VII", group:"tone",
    geo:{ type:"band", p:[[425,690],[421,706],[411,724],[398,742]], w:[11,13] },
    act:"Hạ hàm, nâng xương móng, hỗ trợ nuốt.",
    issue:"Vùng dưới cằm chảy, góc cổ–cằm kém rõ. Nghiên cứu 2025 thấy cơ này thay đổi rõ nhất; nghiên cứu 2018 thấy thiết diện cơ tăng.",
    yoga:"Gập cằm kháng lực: nắm tay đặt dưới cằm, ép cằm xuống vào tay 5 giây × 10. Ép cả mặt lưỡi lên vòm miệng rồi nuốt chậm × 5.",
    warn:"Đau khớp thái dương hàm: dùng lực rất nhẹ.", ev:["guzel","hwang"] },
  { id:"temporalis", vn:"Cơ thái dương", en:"Temporalis", nerve:"TK V3", group:"relax",
    geo:{ type:"fan", apex:[288,466], arc:[[298,300],[280,298],[266,322],[262,378]], n:6 },
    act:"Nâng và kéo lùi hàm dưới; co khi nghiến răng.",
    issue:"Đau đầu vùng thái dương do căng cơ, nghiến răng đêm.",
    yoga:"Đầu ngón tay đặt lên thái dương, há miệng nhẹ, xoay tròn chậm 10 vòng mỗi chiều kèm thở ra dài.",
    warn:"Đau đầu đột ngột, dữ dội: gọi cấp cứu, không xử lý trong lớp." },
  { id:"masseter", vn:"Cơ cắn", en:"Masseter", nerve:"TK V3", group:"relax",
    geo:{ type:"sheet", a:[[283,478],[296,474],[316,476],[332,482]], b:[[296,602],[306,614],[320,624],[334,630]], n:6 },
    act:"Nâng hàm, nhai, nghiến. Xét theo khối lượng, cơ cắn thường được xem là cơ khoẻ nhất cơ thể.",
    issue:"Phì đại cơ làm hàm vuông; nghiến răng, đau khớp thái dương hàm, mặt “gồng” khi stress.",
    yoga:"Tư thế nghỉ hàm (lưỡi chạm vòm, môi khép, răng tách). Day cơ cắn bằng khớp ngón tay theo vòng nhỏ. Tư thế sư tử để xả căng.",
    warn:"Kẹt hàm, há miệng lệch, lục cục kèm đau: chuyển nha sĩ." },
  { id:"buccinator", vn:"Cơ mút (cơ thổi kèn)", en:"Buccinator", nerve:"TK VII", group:"tone",
    geo:{ type:"band", p:[[369,580],[352,580],[334,580],[315,580]], w:[20,42] },
    act:"Ép má vào răng khi nhai, thổi, mút.",
    issue:"Má hóp hoặc chảy. Nghiên cứu 2025: trương lực và độ cứng cơ mút tăng sau 8 tuần tập.",
    yoga:"“Mặt cá”: hóp má rồi cố mỉm cười, 5 giây × 8. Hoặc ngậm hơi, đẩy qua lại hai bên má 30 giây.",
    warn:"Massage trong khoang miệng chỉ làm khi đã học kỹ thuật và vệ sinh.", ev:["guzel"] },
  { id:"frontalis", vn:"Cơ trán", en:"Frontalis", nerve:"TK VII (nhánh thái dương)", group:"relax",
    geo:{ type:"sheet", a:[[296,356],[322,338],[382,334],[428,350]], b:[[284,268],[318,236],[380,222],[430,224]], n:8 },
    act:"Nhướn mày, kéo da trán lên. Là cơ duy nhất nâng được lông mày.",
    issue:"Nếp nhăn ngang trán. Hay co quá mức ở người sụp mí (nhướn bù) và người hay “cười bằng trán”.",
    yoga:"Hai bàn tay giữ da trán phẳng, mở to mắt nhìn lên mà không để trán nhăn, 10 giây × 3. Vuốt từ giữa trán ra thái dương.",
    warn:"Bài nhướn mày lặp nhiều lần có thể làm nếp ngang sâu thêm: với cơ này nên tập thả lỏng." },
  { id:"corrugator", vn:"Cơ cau mày", en:"Corrugator supercilii", nerve:"TK VII", group:"relax",
    geo:{ type:"band", p:[[424,378],[408,370],[384,357],[358,352]], w:[11,6] },
    act:"Kéo đầu mày xuống và vào trong khi cau mày, tập trung, chói nắng.",
    issue:"Nếp dọc giữa hai mày (“số 11”). Nghiên cứu 2025: trương lực giảm sau 8 tuần tập.",
    yoga:"Day vòng nhỏ ở đầu mày (huyệt Toản trúc) rồi vuốt dọc lông mày ra ngoài khi thở ra.",
    warn:"Cau mày nhiều khi đọc có thể do mắt cần kính: gợi ý đi khám mắt.", ev:["guzel"] },
  { id:"procerus", vn:"Cơ tháp mũi", en:"Procerus", nerve:"TK VII", group:"relax", mid:true,
    geo:{ type:"band", p:[[435,414],[435,395],[435,372],[435,350]], w:[16,26] },
    act:"Kéo da giữa hai mày xuống.",
    issue:"Nếp ngang ở gốc mũi.",
    yoga:"Hai ngón trỏ đặt ở gốc mũi, vuốt thẳng lên trán qua huyệt Ấn đường 10 lần khi thở ra dài.", warn:"" },
  { id:"orbicularis_oculi", vn:"Cơ vòng mắt", en:"Orbicularis oculi", nerve:"TK VII", group:"balance",
    geo:{ type:"ring", c:[348,410], o:[62,54], ic:[347,412], i:[42,15] },
    act:"Nhắm, nheo, chớp mắt. Phần ổ mắt tham gia nụ cười thật (Duchenne).",
    issue:"Vết chân chim do phần ngoài co nhiều; mí dưới chùng, bọng mắt do phần mi yếu kèm ứ dịch.",
    yoga:"Bài chữ V: ngón giữa ở đầu mày, ngón trỏ ở đuôi mày, nhìn lên trần và nheo mí dưới lên, 5 giây × 6.",
    warn:"Da quanh mắt mỏng nhất trên mặt: dùng ngón áp út, không chà, không kéo." },
  { id:"nasalis", vn:"Cơ mũi", en:"Nasalis", nerve:"TK VII", group:"balance",
    geo:{ type:"band", p:[[404,508],[407,492],[419,477],[433,469]], w:[11,9] },
    act:"Nở hoặc khép lỗ mũi.",
    issue:"Ít ảnh hưởng thẩm mỹ; hữu ích để dạy nhận biết thở mũi.",
    yoga:"Thở mũi chậm, chú ý cánh mũi nở khi hít vào; ghép với pranayama.", warn:"" },
  { id:"llsan", vn:"Cơ nâng môi trên và cánh mũi", en:"Levator labii superioris alaeque nasi", nerve:"TK VII", group:"balance",
    geo:{ type:"band", p:[[416,420],[411,456],[400,494],[404,556]], w:[7,15] },
    act:"Nâng môi trên, nở cánh mũi (động tác nhăn mũi).",
    issue:"Liên quan phần trên của rãnh mũi má.",
    yoga:"Nhăn mũi thật chậm rồi thả, 6 lần. Vuốt rãnh mũi má từ cánh mũi chéo lên gò má.", warn:"" },
  { id:"lls", vn:"Cơ nâng môi trên", en:"Levator labii superioris", nerve:"TK VII", group:"tone",
    geo:{ type:"band", p:[[358,446],[368,482],[388,522],[404,560]], w:[24,13] },
    act:"Nâng môi trên; góp phần tạo độ đầy vùng má giữa.",
    issue:"Má giữa xẹp, rãnh mũi má rõ hơn khi lão hoá. Nghiên cứu 2018 thấy cơ dày lên (một bên).",
    yoga:"Nâng má: miệng chữ O, môi trên phủ kín răng, mỉm cười để nâng gò má, 5 giây × 10.", warn:"", ev:["hwang"] },
  { id:"zyg_minor", vn:"Cơ gò má bé", en:"Zygomaticus minor", nerve:"TK VII", group:"tone",
    geo:{ type:"band", p:[[322,457],[338,494],[366,533],[390,565]], w:[13,9] },
    act:"Nâng môi trên ra ngoài, tham gia nụ cười.",
    issue:"Độ đầy má trên. Nghiên cứu Northwestern 2018: má trên và má dưới đầy hơn sau 20 tuần.",
    yoga:"Kết hợp bài nâng má; co vừa phải, không cười căng hết cỡ.", warn:"", ev:["alam"] },
  { id:"zyg_major", vn:"Cơ gò má lớn", en:"Zygomaticus major", nerve:"TK VII", group:"tone",
    geo:{ type:"band", p:[[292,478],[312,518],[344,553],[372,574]], w:[22,11] },
    act:"Kéo khoé miệng lên và ra ngoài: cơ chính của nụ cười.",
    issue:"Khoé miệng chùng, mặt trông mệt. Hwang 2018: thiết diện cơ tăng ở cả hai bên sau 8 tuần.",
    yoga:"Mỉm cười ngậm môi, nâng khoé miệng thật chậm về phía đuôi mắt, giữ 10 giây × 6.", warn:"", ev:["hwang"] },
  { id:"lao", vn:"Cơ nâng góc miệng", en:"Levator anguli oris", nerve:"TK VII", group:"tone",
    geo:{ type:"band", p:[[383,497],[383,521],[379,548],[375,571]], w:[14,9] },
    act:"Nâng góc miệng thẳng lên; nằm sâu dưới cơ nâng môi trên.",
    issue:"Khoé miệng trễ.",
    yoga:"Ngón trỏ đặt ở khoé miệng tạo lực cản nhẹ, nâng khoé lên chống lại ngón tay, 5 giây × 8.", warn:"" },
  { id:"risorius", vn:"Cơ cười ngang", en:"Risorius", nerve:"TK VII", group:"balance",
    geo:{ type:"band", p:[[372,578],[350,576],[322,572],[300,568]], w:[7,12] },
    act:"Kéo khoé miệng sang ngang.",
    issue:"Cười căng ngang lâu dài có thể tạo nếp ở má dưới. Cơ có nhiều biến thể; một số người không có.",
    yoga:"Không cần tập riêng; hướng dẫn cười “lên” về phía đuôi mắt thay vì “ngang”.", warn:"" },
  { id:"orbicularis_oris", vn:"Cơ vòng môi", en:"Orbicularis oris", nerve:"TK VII", group:"balance", mid:true,
    geo:{ type:"ring", c:[435,584], o:[84,44], ic:[435,578], i:[60,6] },
    act:"Khép, chu, mím môi; phát âm.",
    issue:"Nếp nhăn dọc quanh môi, nặng hơn khi hút thuốc. Nghiên cứu 2025: trương lực giảm, độ đàn hồi tăng.",
    yoga:"Chu môi rồi cười rộng, luân phiên 10 lần. Ép hai môi vào nhau 5 giây rồi thả.",
    warn:"Herpes môi đang bùng phát: không thao tác vùng môi.", ev:["guzel"] },
  { id:"dao", vn:"Cơ hạ góc miệng", en:"Depressor anguli oris", nerve:"TK VII", group:"relax",
    geo:{ type:"fan", apex:[375,582], arc:[[394,670],[378,668],[356,660],[338,648]], n:6 },
    act:"Kéo khoé miệng xuống (vẻ buồn, chê).",
    issue:"Rãnh từ khoé miệng xuống cằm (rãnh marionette), mặt trông buồn.",
    yoga:"Day xoắn nhẹ từ khoé miệng xuống bờ hàm, rồi tập nâng khoé để cân bằng.", warn:"" },
  { id:"dli", vn:"Cơ hạ môi dưới", en:"Depressor labii inferioris", nerve:"TK VII", group:"balance",
    geo:{ type:"sheet", a:[[396,607],[404,608],[414,610],[424,612]], b:[[386,662],[396,668],[406,672],[416,676]], n:5 },
    act:"Kéo môi dưới xuống và ra ngoài.",
    issue:"Ít khi cần tập riêng.",
    yoga:"Đi kèm bài cổ: đẩy môi dưới ra khi nhìn chéo lên.", warn:"" },
  { id:"mentalis", vn:"Cơ cằm", en:"Mentalis", nerve:"TK VII", group:"relax",
    geo:{ type:"band", p:[[428,622],[427,638],[424,655],[420,672]], w:[11,18] },
    act:"Nhăn da cằm, đẩy môi dưới lên.",
    issue:"Cằm sần “vỏ cam” khi khép môi; hay gặp khi môi không khép kín tự nhiên (thở miệng, răng hô).",
    yoga:"Day tròn cằm 20 giây; nhắc khép môi nhẹ, không gồng cằm.",
    warn:"Cằm luôn gồng khi khép môi: gợi ý khám nha khoa hoặc tai mũi họng." }
],
muscleOrder: ["trapezius","platysma","scm","digastric","temporalis","masseter","buccinator","frontalis","corrugator","procerus","orbicularis_oculi","nasalis","llsan","lls","zyg_minor","zyg_major","lao","risorius","orbicularis_oris","dao","dli","mentalis"],

/* ---------------- BẠCH HUYẾT ---------------- */
nodes: [
  { id:"pre", vn:"Hạch trước tai (mang tai)", en:"Preauricular / parotid", x:271, y:466,
    from:"Trán, thái dương, mí mắt phần ngoài, má trên.", to:"Hạch cổ sâu.",
    how:"Ngón trỏ và giữa xoè chữ V ôm quanh tai, vòng tròn tĩnh tại thật nhẹ 5–10 lần rồi vuốt xuống cổ." },
  { id:"retro", vn:"Hạch sau tai (chũm)", en:"Retroauricular / mastoid", x:252, y:540,
    from:"Da đầu vùng đỉnh và thái dương sau, mặt sau vành tai.", to:"Hạch cổ nông và cổ sâu.",
    how:"Cùng thao tác chữ V với hạch trước tai." },
  { id:"buccal", vn:"Hạch má (cơ mút)", en:"Buccal / facial", x:336, y:548,
    from:"Mũi, má, môi trên.", to:"Hạch dưới hàm.",
    how:"Lòng ngón tay phẳng, kéo da rất nhẹ từ cánh mũi ngang ra góc hàm." },
  { id:"mand", vn:"Hạch hàm dưới", en:"Mandibular", x:342, y:642,
    from:"Má dưới, môi.", to:"Hạch dưới hàm.", how:"Đi kèm thao tác dọc bờ hàm." },
  { id:"subm", vn:"Hạch dưới hàm", en:"Submandibular", x:366, y:690,
    from:"Má, mũi, môi trên, phần ngoài môi dưới, lợi, góc mắt trong.", to:"Hạch cổ sâu.",
    how:"Từ giữa cằm vuốt dọc dưới xương hàm ra góc hàm, rồi xuống cổ." },
  { id:"subment", vn:"Hạch dưới cằm", en:"Submental", x:435, y:712, mid:true,
    from:"Giữa môi dưới, cằm, đầu lưỡi, sàn miệng.", to:"Hạch dưới hàm và hạch cổ sâu.",
    how:"Ngón tay đặt dưới cằm, kéo da nhẹ ra hai bên về phía góc hàm." },
  { id:"cerv_sup", vn:"Hạch cổ nông", en:"Superficial cervical", x:326, y:712,
    from:"Vùng sau tai, tuyến mang tai, da cổ.", to:"Hạch cổ sâu.",
    how:"Lòng bàn tay phẳng, vuốt từ dưới tai xuống xương đòn." },
  { id:"cerv_deep", vn:"Hạch cổ sâu (chuỗi cảnh trong)", en:"Deep cervical", x:352, y:744,
    from:"Gần như toàn bộ đầu, mặt, cổ.", to:"Thân bạch huyết cảnh, rồi về hội lưu tĩnh mạch.",
    how:"Vuốt dọc cổ bên (theo cơ ức đòn chũm) từ trên xuống, rất nhẹ." },
  { id:"supra", vn:"Hạch thượng đòn (terminus)", en:"Supraclavicular / venous angle", x:340, y:858,
    from:"Toàn bộ dòng bạch huyết đầu cổ trước khi đổ vào máu.", to:"Hội lưu tĩnh mạch cảnh trong và dưới đòn.",
    how:"Bước đầu tiên và cuối cùng của mọi buổi dẫn lưu: ngón tay phẳng đặt vào hõm trên xương đòn, kéo da nhẹ vào trong và xuống 10 lần." }
],
flows: [
  "M362,282 Q300,360 274,452", "M316,424 Q292,440 276,458", "M402,482 Q352,500 339,542 Q338,618 362,682",
  "M392,568 Q372,622 366,680", "M428,714 Q402,712 374,696", "M271,482 Q300,620 348,734",
  "M254,552 Q282,640 322,704", "M366,698 L355,734", "M328,722 Q332,800 338,846", "M352,754 Q348,812 342,846"
],
flowsMid: ["M435,642 L435,700"],
mld: [
  { t:"Thở bụng", img:"mld_1", n:[], d:"5 nhịp: hít vào bụng phồng, thở ra dài gấp đôi. Thay đổi áp lực ngực–bụng hỗ trợ dòng chảy trong ống ngực." },
  { t:"Mở “cửa” thượng đòn", img:"mld_2", n:["supra"], d:"Ngón tay phẳng đặt vào hõm trên xương đòn, kéo da rất nhẹ vào trong và xuống, 10 lần." },
  { t:"Cổ bên", img:"mld_3", n:["cerv_deep","cerv_sup"], d:"Lòng bàn tay phẳng, vuốt từ dưới dái tai dọc cổ xuống xương đòn, 10 lần mỗi bên." },
  { t:"Quanh tai", img:"mld_4", n:["pre","retro"], d:"Ngón trỏ và giữa xoè chữ V ôm quanh tai, vòng tròn tĩnh tại 5–10 lần, rồi vuốt xuống cổ." },
  { t:"Dưới cằm → dưới hàm", img:"mld_5", n:["subment","subm"], d:"Từ giữa cằm vuốt dọc mặt dưới xương hàm ra góc hàm, nối tiếp xuống cổ." },
  { t:"Má và cánh mũi", img:"mld_6", n:["buccal","mand","subm"], d:"Từ cánh mũi kéo da ngang qua má về góc hàm và trước tai, theo ba đường." },
  { t:"Quanh mắt", img:"mld_7", n:["pre"], d:"Ngón áp út rất nhẹ, từ khoé mắt trong theo bờ ổ mắt dưới ra đuôi mắt, qua thái dương về trước tai." },
  { t:"Trán và kết thúc", img:"mld_8", n:["pre","cerv_deep","supra"], d:"Từ giữa trán vuốt ra thái dương, xuống trước tai, dọc cổ về thượng đòn; kết thúc bằng 3 nhịp ở thượng đòn." }
],

/* ---------------- HUYỆT KINH ĐIỂN ---------------- */
points: [
  { id:"yintang", vn:"Ấn đường", code:"EX-HN3 / GV29", x:435, y:366, mid:true, loc:"Chính giữa hai đầu lông mày.", use:"An thần, đau đầu vùng trán, nghẹt mũi; thư giãn nếp cau mày.", warn:"" },
  { id:"gb14", vn:"Dương bạch", code:"GB14", x:352, y:304, loc:"Trên điểm giữa lông mày 1 thốn, thẳng trên con ngươi.", use:"Đau đầu vùng trán, nếp nhăn trán.", warn:"" },
  { id:"yuyao", vn:"Ngư yêu", code:"EX-HN4", x:352, y:350, loc:"Giữa lông mày, thẳng trên con ngươi.", use:"Mỏi mắt, nặng mí.", warn:"" },
  { id:"bl2", vn:"Toản trúc", code:"BL2", x:397, y:362, loc:"Chỗ lõm ở đầu trong lông mày.", use:"Mỏi mắt, đau đầu, cau mày.", warn:"" },
  { id:"te23", vn:"Ty trúc không", code:"TE23", x:300, y:366, loc:"Chỗ lõm ở đuôi lông mày.", use:"Đau đầu bên, giật mí.", warn:"" },
  { id:"taiyang", vn:"Thái dương", code:"EX-HN5", x:276, y:392, loc:"Hõm thái dương, sau điểm giữa đuôi mày và đuôi mắt khoảng 1 thốn.", use:"Đau đầu, mỏi mắt, căng cơ thái dương.", warn:"" },
  { id:"gb1", vn:"Đồng tử liêu", code:"GB1", x:290, y:412, loc:"Ngoài khoé mắt ngoài khoảng 0,5 thốn.", use:"Mỏi mắt; vùng vết chân chim.", warn:"" },
  { id:"bl1", vn:"Tình minh", code:"BL1", x:392, y:414, loc:"Hơi trên khoé mắt trong.", use:"Mỏi mắt.", warn:"Rất gần nhãn cầu: chỉ ấn cực nhẹ, không day mạnh." },
  { id:"st1", vn:"Thừa khấp", code:"ST1", x:352, y:434, loc:"Thẳng dưới con ngươi, giữa nhãn cầu và bờ dưới ổ mắt.", use:"Bọng mắt (kết hợp dẫn lưu), mỏi mắt.", warn:"Ấn trên bờ xương, không ấn vào nhãn cầu." },
  { id:"st2", vn:"Tứ bạch", code:"ST2", x:352, y:452, loc:"Chỗ lõm của lỗ dưới ổ mắt.", use:"Da mặt, mắt, đau mặt.", warn:"" },
  { id:"si18", vn:"Quyền liêu", code:"SI18", x:308, y:488, loc:"Bờ dưới xương gò má, thẳng dưới đuôi mắt.", use:"Đau mặt; dùng nhiều trong các bài nâng cơ.", warn:"" },
  { id:"li20", vn:"Nghênh hương", code:"LI20", x:393, y:506, loc:"Cạnh trung điểm cánh mũi, trong rãnh mũi má.", use:"Nghẹt mũi; vùng rãnh mũi má.", warn:"" },
  { id:"st3", vn:"Cự liêu", code:"ST3", x:352, y:518, loc:"Thẳng dưới con ngươi, ngang bờ dưới cánh mũi.", use:"Đau mặt; vùng má giữa.", warn:"" },
  { id:"st7", vn:"Hạ quan", code:"ST7", x:282, y:476, loc:"Hõm trước tai, dưới cung gò má (sờ khi ngậm miệng).", use:"Khớp thái dương hàm, đau răng, căng hàm.", warn:"" },
  { id:"gv26", vn:"Nhân trung (Thuỷ câu)", code:"GV26", x:435, y:541, mid:true, loc:"Điểm 1/3 trên của rãnh nhân trung.", use:"Truyền thống dùng để hồi tỉnh khi ngất.", warn:"Người ngất thật cần gọi cấp cứu 115 trước." },
  { id:"st4", vn:"Địa thương", code:"ST4", x:358, y:577, loc:"Ngoài khoé miệng khoảng 0,4 thốn.", use:"Vùng khoé miệng và rãnh cười.", warn:"" },
  { id:"st6", vn:"Giáp xa", code:"ST6", x:312, y:590, loc:"Trên góc hàm khoảng một khoát ngón tay, chỗ cơ cắn nổi khi cắn chặt.", use:"Nghiến răng, căng hàm, đau răng.", warn:"" },
  { id:"cv24", vn:"Thừa tương", code:"CV24", x:435, y:619, mid:true, loc:"Chỗ lõm giữa rãnh cằm–môi.", use:"Vùng cằm, tiết nước bọt.", warn:"" },
  { id:"te17", vn:"Ế phong", code:"TE17", x:266, y:536, loc:"Sau dái tai, trong hõm giữa xương chũm và góc hàm.", use:"Ù tai, đau mặt.", warn:"Vùng có thần kinh mặt đi ra: ấn nhẹ." },
  { id:"st12", vn:"Khuyết bồn", code:"ST12", x:325, y:862, loc:"Giữa hố trên xương đòn.", use:"Truyền thống dùng cho ho, đau họng. Trùng với vùng “terminus” của bạch huyết.", warn:"Ấn nông, không ấn sâu." }
],

/* ---------------- LINH KHU 49 – NGŨ SẮC ---------------- */
zones: [
  { id:"z_ting", vn:"Đình (giữa trán trên)", org:"Đầu, mặt", x:435, y:250, mid:true, src:"庭者，首面也" },
  { id:"z_qs", vn:"Khuyết thượng (trên ấn đường)", org:"Yết hầu (họng)", x:435, y:318, mid:true, src:"闕上者，咽喉也" },
  { id:"z_qz", vn:"Khuyết trung (giữa hai mày)", org:"Phế", x:435, y:364, mid:true, src:"闕中者，肺也" },
  { id:"z_xj", vn:"Hạ cực (gốc mũi, giữa hai mắt)", org:"Tâm", x:435, y:405, mid:true, src:"下極者，心也" },
  { id:"z_zx", vn:"Trực hạ (sống mũi)", org:"Can", x:435, y:452, mid:true, src:"直下者，肝也" },
  { id:"z_gz", vn:"Cạnh vùng Can", org:"Đởm", x:420, y:450, src:"肝左者，膽也" },
  { id:"z_xc", vn:"Hai bên trên đầu mũi", org:"Tiểu trường", x:419, y:486, src:"面王以上者，小腸也" },
  { id:"z_mw", vn:"Đầu mũi (Diện vương)", org:"Tỳ", x:435, y:500, mid:true, src:"下者，脾也" },
  { id:"z_fs", vn:"Cánh mũi", org:"Vị", x:401, y:514, src:"方上者，胃也" },
  { id:"z_zy", vn:"Giữa má", org:"Đại trường", x:364, y:506, src:"中央者，大腸也" },
  { id:"z_jd", vn:"Má ngoài (kẹp vùng Đại trường)", org:"Thận", x:320, y:512, src:"挾大腸者，腎也" },
  { id:"z_qi", vn:"Dưới vùng Thận", org:"Rốn", x:324, y:542, src:"當腎者，臍也" },
  { id:"z_rz", vn:"Nhân trung (dưới đầu mũi)", org:"Bàng quang, tử xứ (tử cung)", x:435, y:546, mid:true, src:"面王以下者，膀胱子處也" },
  { id:"z_qu", vn:"Gò má", org:"Vai", x:318, y:462, src:"顴者，肩也" },
  { id:"z_qh", vn:"Sau gò má", org:"Cánh tay", x:291, y:470, src:"顴後者，臂也" },
  { id:"z_bx", vn:"Dưới vùng cánh tay", org:"Bàn tay", x:292, y:502, src:"臂下者，手也" },
  { id:"z_mn", vn:"Trên khoé mắt trong", org:"Ngực, vú", x:397, y:394, src:"目內眥上者，膺乳也" },
  { id:"z_js", vn:"Phía ngoài má, sát tai", org:"Lưng", x:277, y:440, src:"挾繩而上者，背也" },
  { id:"z_gu", vn:"Từ góc hàm đi xuống", org:"Đùi", x:300, y:600, src:"循牙車以下者，股也" },
  { id:"z_xi", vn:"Giữa bờ hàm", org:"Gối", x:330, y:638, src:"中央者，膝也" },
  { id:"z_jing", vn:"Dưới vùng gối", org:"Cẳng chân", x:362, y:662, src:"膝以下者，脛也" },
  { id:"z_zu", vn:"Dưới vùng cẳng chân", org:"Bàn chân", x:394, y:678, src:"當脛以下者，足也" }
],

/* ---------------- DIỆN CHẨN ----------------
   Vùng: đồ hình phản chiếu nội tạng (nguyên văn trích “Thực hành Diện Chẩn – Điều khiển liệu pháp”, GS.TS Bùi Quốc Châu).
   Điểm: “tứ đại huyệt”. Vị trí trên hình là gần đúng để minh hoạ. */
dcAreas: [
  { id:"dc_nose", kind:"area", mid:true, geo:{ type:"band", p:[[435,398],[435,432],[435,470],[435,506]], w:[22,30] },
    vn:"Sống mũi (sơn căn → đầu mũi)", org:"Tim, động mạch phổi · Xương ức, thực quản, khí quản · Cột sống",
    quote:"“Đầu mũi đến Sơn căn” → Tim, động mạch phổi; “Sống mũi” → Xương ức – Thực quản, khí quản",
    note:"Ba đồ hình chồng lên cùng một vùng. Theo đồ hình cột sống: gốc mũi ứng với cổ, thân sống mũi với lưng giữa, đầu mũi với thắt lưng.", s:["dc_map","dc_spine"] },
  { id:"dc_lung", kind:"area", geo:{ type:"ell", c:[348,437], r:[34,9] }, vn:"Dưới mí mắt dưới (ngoạ tàm)", org:"Phổi", quote:"“Vùng dưới ngọa tàm (mí mắt dưới)”", s:["dc_map"] },
  { id:"dc_liver", kind:"area", single:true, geo:{ type:"ell", c:[326,516], r:[26,15] }, vn:"Má phải, dưới xương gò má", org:"Gan – Mật",
    quote:"“Vùng dưới khu vực vừa nêu trên (phổi): Mép phải, dưới xương gò má bên mặt”", note:"Bên phải của người được vẽ, tức bên trái hình.", s:["dc_map"] },
  { id:"dc_stomach", kind:"area", single:true, geo:{ type:"ell", c:[544,516], r:[26,15] }, vn:"Má trái, dưới xương gò má", org:"Dạ dày, lách",
    quote:"“Cũng vùng trên nhưng bên trái”", note:"Bên trái của người được vẽ, tức bên phải hình.", s:["dc_map"] },
  { id:"dc_lip", kind:"line", mid:true, d:"M374,573 Q405,556 435,563 Q465,556 498,573", vn:"Bờ môi trên", org:"Dạ dày, tuỵ (lá mía)", quote:"“Bờ môi trên”", s:["dc_map"] },
  { id:"dc_si", kind:"line", mid:true, d:"M368,566 Q404,546 435,554 Q466,546 502,566 M384,598 Q435,620 486,598", vn:"Viền trắng quanh môi trên và mép dưới môi dưới", org:"Ruột non",
    quote:"“Viền trắng quanh môi trên và phần dưới của bờ môi dưới”", s:["dc_map"] },
  { id:"dc_chin", kind:"area", mid:true, geo:{ type:"ell", c:[435,668], r:[24,20] }, vn:"Ụ cằm xuống chót cằm", org:"Tử cung, buồng trứng, bàng quang", quote:"“Chỗ lồi nhất của ụ cằm xuống chót cằm”", s:["dc_map"] },
  { id:"dc_kidney", kind:"area", geo:{ type:"ell", c:[364,560], r:[8,15] }, vn:"Từ khoé miệng lên ngang giữa nhân trung", org:"Thận, tuyến thượng thận",
    quote:"“Từ phần khóe trở lên đụng đường ngang qua giữa Nhân trung”", s:["dc_map"] },
  { id:"dc_ribs", kind:"line", d:"M390,546 Q360,540 326,526", vn:"Từ nếp mũi má chéo về dưới gò má", org:"Bờ sườn",
    quote:"“Từ nếp nhăn mũi má chéo xuống dưới xương gò má (giữa rãnh Nhân trung)”", note:"Mô tả gốc ngắn; đường trên hình là cách hiểu gần đúng.", s:["dc_map"] }
],
dcPoints: [
  { id:"dc26", vn:"Huyệt 26", x:435, y:366, mid:true, loc:"Trung điểm giữa hai đầu lông mày.", use:"Thư giãn cơ, an thần, giảm đau, lợi tiểu, hạ sốt.", s:["dc_official","dc_4"] },
  { id:"dc19", vn:"Huyệt 19", x:435, y:533, mid:true, loc:"Đỉnh của rãnh nhân trung, ngay dưới chân mũi.", use:"Nâng khí, tăng tỉnh táo, hỗ trợ hô hấp; dùng khi choáng.", s:["dc_official","dc_4"] },
  { id:"dc127", vn:"Huyệt 127", x:435, y:630, mid:true, loc:"Dưới môi dưới, điểm cao nhất của đường cong ụ cằm.", use:"An thần, làm ấm bụng, điều hoà nhu động ruột.", s:["dc_4"] },
  { id:"dc0", vn:"Huyệt 0", x:262, y:488, loc:"Trên rãnh bình tai (chỗ lõm ở chân bình tai).", use:"Ổn định thần kinh, điều hoà tim và huyết áp, giảm đau.", s:["dc_4"] }
],

/* ---------------- KINH LẠC TRÊN MẶT (sơ đồ) ---------------- */
meridians: [
  { k:"Bàng quang", c:"#008300", d:"M392,414 L397,362 Q398,300 400,222", lab:[255,252], to:[399,262] },
  { k:"Đởm", c:"#1baf7a", d:"M290,412 L266,488 M266,488 Q262,452 276,440 Q270,360 290,262 Q322,280 352,304 L352,228", lab:[255,330], to:[279,340] },
  { k:"Tam tiêu", c:"#eda100", d:"M266,536 Q250,500 258,462 L262,446 L270,420 Q284,392 300,366", lab:[255,398], to:[281,392] },
  { k:"Tiểu trường", c:"#e87ba4", d:"M300,640 Q296,560 308,488 Q286,474 264,466", lab:[255,470], to:[288,478] },
  { k:"Vị", c:"#eb6834", d:"M352,434 L352,452 L352,518 L358,577 Q350,610 342,640 Q322,620 312,590 Q296,530 282,476 Q282,380 290,262 M342,640 Q368,700 392,760 Q402,820 410,866 Q370,868 325,862", lab:[255,560], to:[304,560] },
  { k:"Đại trường", c:"#2a78d6", d:"M352,760 Q372,650 412,560 L418,540 Q432,532 448,528 L478,506", lab:[255,700], to:[367,700] }
],
meridiansMid: [
  { k:"Đốc mạch", c:"#4a3aa7", d:"M435,214 L435,566", lab:[452,236], to:[436,244] },
  { k:"Nhâm mạch", c:"#e34948", d:"M435,619 L435,895", lab:[452,806], to:[436,806] }
],

/* ---------------- BÀI TẬP ---------------- */
exercises: [
  { img:"ex_cheek", t:"Nâng má", m:"Cơ nâng môi trên, cơ gò má", steps:["Miệng chữ O dọc, môi trên phủ kín răng.","Mỉm cười để nâng gò má, đầu ngón trỏ đặt nhẹ trên gò má.","Giữ 5 giây, thả chậm, lặp 10 lần."], note:"Đây là bài “Cheek Lifter” trong chương trình nghiên cứu Northwestern.", s:["sd2018"] },
  { img:"ex_v", t:"Chữ V", m:"Cơ vòng mắt (phần mi dưới)", steps:["Ngón giữa ở đầu mày, ngón trỏ ở đuôi mày.","Nhìn lên trần, nheo mí dưới lên.","Giữ 5 giây × 6, kết thúc bằng nhắm mắt thư giãn 10 giây."], note:"Ấn nhẹ, không kéo da quanh mắt.", s:[] },
  { img:"ex_lion", t:"Sư tử (Simhasana)", m:"Toàn mặt, lưỡi, cổ trước", steps:["Hít vào bằng mũi.","Thở ra bằng miệng, há rộng, thè lưỡi dài xuống cằm, mắt nhìn lên.","Lặp 3 lần, rồi thả lỏng mặt hoàn toàn."], note:"Xả căng sau bài tăng cường. Đau khớp hàm: há vừa phải.", s:["hyp"] },
  { img:"ex_chin", t:"Gập cằm kháng lực", m:"Cơ hai bụng, nhóm trên móng", steps:["Nắm tay đặt dưới cằm.","Ép cằm xuống vào nắm tay, cổ giữ dài.","Giữ 5 giây, lặp 10 lần."], note:"Cơ hai bụng thay đổi rõ nhất trong nghiên cứu 2025.", s:["guzel"] },
  { img:"ex_jaw", t:"Thả lỏng hàm", m:"Cơ cắn, cơ thái dương", steps:["Lưỡi chạm vòm sau răng cửa, môi khép, răng tách.","Khớp ngón tay day vòng nhỏ trên cơ cắn 30 giây.","Chuyển lên thái dương, vừa day vừa thở ra dài."], note:"Kẹt hàm, đau cấp: chuyển nha sĩ.", s:[] },
  { img:"ex_lymph", t:"Mở cửa thượng đòn", m:"Hạch thượng đòn (terminus)", steps:["Ngón tay phẳng đặt vào hõm trên xương đòn.","Kéo da thật nhẹ vào trong và xuống.","10 lần, đầu và cuối mọi buổi dẫn lưu."], note:"Lực chỉ đủ kéo căng da, không ấn sâu.", s:["abmp_mld"] }
],

/* ---------------- NGUỒN GỐC ---------------- */
streams: [
  { img:"o_yoga", tag:"Yoga cổ điển", t:"Tư thế sư tử", d:"Simhasana trong Hatha Yoga Pradipika (TK 15) huy động lưỡi, hàm, mắt, cổ trước.", s:["hyp"] },
  { img:"o_tcm", tag:"Đông y", t:"Mặt là tấm gương", d:"Nội Kinh coi mặt là nơi khí huyết dồn lên và là bản đồ tạng phủ.", s:["lk4","lk49"] },
  { img:"o_kobido", tag:"Nhật Bản", t:"Kobido", d:"Massage mặt từ năm 1472 với hơn 40 kỹ thuật tay.", s:["kobido"] },
  { img:"o_west", tag:"Phương Tây", t:"Thể dục cho mặt", d:"Từ báo chí 1970–80, sách Facercise (1995) đến Face Yoga Method (2006).", s:["facercise","takatsu"] }
],
timeline: [
  { y:"Khoảng TK 2–1 TCN", tag:"dongy", t:"Hoàng Đế Nội Kinh", d:"Linh Khu thiên 49 đặt cả cơ thể lên khuôn mặt (gò má ứng với vai, sống mũi với Can...). Thiên 4: khí huyết của 12 kinh, 365 lạc đều lên mặt.", s:["lk49","lk4"] },
  { y:"TK 15", tag:"yoga", t:"Simhasana trong Hatha Yoga Pradipika", d:"Tư thế sư tử được mô tả trong chương 1: bài “face yoga” cổ điển nhất còn được dạy.", s:["hyp"] },
  { y:"1472", tag:"chau-a", t:"Kobido, Nhật Bản", d:"Theo truyền thuyết, hai bậc thầy Anma thi nhau tìm kỹ thuật massage mặt tinh tế nhất; phái thắng cuộc lập nên Kobido.", s:["kobido"] },
  { y:"1932", tag:"tay", t:"Dẫn lưu bạch huyết Vodder", d:"Emil và Estrid Vodder phát triển kỹ thuật ở Cannes cho bệnh nhân sưng hạch cổ mạn tính.", s:["vodder"] },
  { y:"1970s–80s", tag:"tay", t:"Tập cơ mặt lên báo Mỹ", d:"Các bài “thể dục cho khuôn mặt” xuất hiện; nguồn gốc chính xác của face yoga hiện đại vẫn chưa rõ.", s:["ctv"] },
  { y:"Đầu thập niên 1980", tag:"vn", t:"Diện chẩn Bùi Quốc Châu", d:"Hình thành Diện chẩn – Điều khiển liệu pháp: 26 huyệt mốc, các huyệt đánh số từ 0 đến 555 và nhiều đồ hình phản chiếu cơ thể trên mặt.", s:["lc_dc","dc_sinh"] },
  { y:"1988", tag:"tay", t:"Facial Reflexology (Sorensensistem)", d:"Lone Sorensen (Đan Mạch) kết hợp Diện chẩn với truyền thống Nam Mỹ và giải phẫu học.", s:["sorensen"] },
  { y:"1995", tag:"tay", t:"Facercise", d:"Carole Maggio xuất bản Facercise, đưa “tập thể hình cho mặt” ra đại chúng.", s:["facercise"] },
  { y:"2006", tag:"chau-a", t:"Face Yoga Method", d:"Fumiko Takatsu bắt đầu hệ thống bài tập sau một tai nạn xe năm 35 tuổi; về sau mở đào tạo giáo viên.", s:["takatsu"] },
  { y:"2007", tag:"yoga", t:"The Yoga Face", d:"Annelise Hagen, giáo viên yoga ở New York, xuất bản sách; định vị face yoga là lựa chọn thay cho Botox, filler.", s:["hagen","nbc"] },
  { y:"2014", tag:"khoahoc", t:"Tổng quan hệ thống đầu tiên", d:"9 nghiên cứu, đều ở Nam Mỹ: kết quả tốt nhưng chất lượng chưa đủ để kết luận.", s:["vanborsel"] },
  { y:"2018", tag:"khoahoc", t:"Northwestern / JAMA Dermatology", d:"32 bài do Gary Sikorski thiết kế; 16/27 phụ nữ hoàn thành 20 tuần; tuổi ước tính giảm từ 50,8 xuống 48,1.", s:["alam","sd2018"] },
  { y:"2021–22", tag:"vn", t:"Face yoga vào studio Việt Nam", d:"Ally Vân Anh và Lenka Seminova có chứng chỉ Face Yoga Method (2021), mở workshop ở Sài Gòn; khoá online của Nguyễn Hiếu vượt 18.000 học viên.", s:["athas","unica"] },
  { y:"2024", tag:"khoahoc", t:"Tổng quan hệ thống thứ hai", d:"7 nghiên cứu (Revista CEFAC): bài tập có vẻ có ích nhưng bằng chứng vẫn chưa đủ.", s:["scielo"] },
  { y:"2024–25", tag:"chau-a", t:"“Slow aging” ở Hàn Quốc", d:"Olive Young: nhóm sản phẩm slow aging tăng hơn 60% năm 2024.", s:["oliveyoung"] },
  { y:"2025", tag:"khoahoc", t:"Đo cơ bằng Myoton", d:"8 tuần, 12 phụ nữ: cơ nông dịu lại, cơ mút và cơ hai bụng khoẻ lên, mọi cơ đàn hồi hơn.", s:["guzel"] }
],

/* ---------------- NGÁCH ---------------- */
niches: [
  { t:"Face yoga + cổ vai gáy cho dân văn phòng", img:"n_office", fit:5, demand:"Cao", ev:"Vừa", tags:["offline","online","b2b"], d:"Gần nhất với chuyên môn yoga phục hồi, dễ bán cho doanh nghiệp." },
  { t:"Thả lỏng hàm, nghiến răng", img:"n_jaw", fit:5, demand:"Trung bình", ev:"Vừa", tags:["offline","refer"], d:"Tư thế nghỉ hàm, thở, thả lỏng cơ cắn; giới thiệu hai chiều với nha sĩ." },
  { t:"Tiền mãn kinh và mãn kinh", img:"n_meno", fit:4, demand:"Cao", ev:"Vừa", tags:["offline","online"], d:"Da mỏng và khô nhanh, kèm bốc hoả, mất ngủ: face yoga, thở làm dịu, chăm sóc da cơ bản." },
  { t:"Sau sinh", img:"n_post", fit:4, demand:"Trung bình", ev:"Yếu", tags:["offline","online"], d:"Cổ vai gáy do bế con, mặt phù, thiếu ngủ; buổi ngắn 15–20 phút, tập ngồi." },
  { t:"Dẫn lưu bạch huyết và gua sha", img:"n_guasha", fit:4, demand:"Cao", ev:"Yếu", tags:["offline","product"], d:"Dễ thấy ngay (giảm bọng buổi sáng), hợp video; cần học kỹ thuật tay." },
  { t:"Mỏi mắt màn hình", img:"n_eye", fit:4, demand:"Trung bình", ev:"Vừa", tags:["online","b2b"], d:"Quy tắc 20-20-20, chớp mắt chủ động, thả lỏng cơ vòng mắt." },
  { t:"Thử thách online 21–28 ngày", img:"n_online", fit:4, demand:"Cao", ev:"—", tags:["online"], d:"Mô hình đã chạy ở Việt Nam (Unica, Udemy); cần ảnh trước–sau chuẩn hoá." },
  { t:"Chương trình cho doanh nghiệp", img:"n_corp", fit:4, demand:"Trung bình", ev:"—", tags:["b2b"], d:"Gói 6–8 buổi “giải toả căng thẳng khuôn mặt và cổ” cho nhân viên." },
  { t:"Người cao tuổi: biểu cảm, nuốt, phát âm", fit:3, demand:"Đang lên", ev:"Vừa", tags:["refer"], d:"Theo mô hình Brazil; phải phối hợp chuyên viên y tế." },
  { t:"Nam giới: đường hàm, căng thẳng", fit:3, demand:"Đang lên", ev:"Yếu", tags:["online"], d:"Dùng ngôn ngữ “tập luyện” thay vì “làm đẹp”." },
  { t:"Kobido, massage mặt thủ công", fit:3, demand:"Cao", ev:"Yếu", tags:["spa"], d:"Hợp tác spa; cần nhiều giờ thực hành tay nhất." },
  { t:"Đào tạo giáo viên face yoga", fit:3, demand:"Trung bình", ev:"—", tags:["online","offline"], d:"Nên làm sau khi đã dạy ổn định 1–2 năm." },
  { t:"Sản phẩm: dầu, đá gua sha, thiết bị", fit:2, demand:"Cao", ev:"Yếu", tags:["product"], d:"Biên lợi nhuận tốt nhưng dễ trượt sang quảng cáo quá đà." },
  { t:"Đồng hành sau thẩm mỹ", fit:2, demand:"Trung bình", ev:"Yếu", tags:["refer"], d:"Khi nào tập lại sau tiêm botox, filler: theo chỉ định bác sĩ." }
],

/* ---------------- CHĂM SÓC DA ---------------- */
pairs: [
  { dong:"Phế chủ bì mao", dongD:"Phế làm chủ da và lông.", tay:"Hàng rào bảo vệ da", tayD:"Lớp sừng, lipid, hệ vi sinh trên da.", act:"Rửa mặt dịu nhẹ, dưỡng ẩm có ceramide, thở mũi.", s:["sv9"] },
  { dong:"Tỳ chủ cơ nhục", dongD:"Vẻ tươi hiện ở môi.", tay:"Dinh dưỡng và trương lực cơ", tayD:"Đủ đạm; đường huyết cao làm collagen cứng (đường hoá).", act:"Ăn đủ đạm, hạn chế đường, tập cơ mặt.", s:["sv9"] },
  { dong:"Tâm, vẻ tươi ở mặt", dongD:"Khí huyết đầy đủ thì mặt hồng hào.", tay:"Vi tuần hoàn, hệ tự chủ", tayD:"Stress kéo dài làm da xỉn.", act:"Thở chậm, massage, ngủ đủ.", s:["sv9"] },
  { dong:"Can chủ sơ tiết", dongD:"Cảm xúc dồn nén gây khí trệ.", tay:"Căng cơ do cảm xúc", tayD:"Gồng hàm, cau mày; rối loạn nội tiết.", act:"Thả lỏng hàm và trán, quản lý stress.", s:[] },
  { dong:"Thận tàng tinh", dongD:"Nữ 35 tuổi mạch Dương minh suy, mặt bắt đầu khô.", tay:"Lão hoá nội tiết", tayD:"5 năm đầu mãn kinh mất khoảng 30% collagen.", act:"Dưỡng ẩm, retinoid, chống nắng; khám nội tiết.", s:["sv1","aad"] },
  { dong:"Ngoại tà", dongD:"Phong, hàn, thấp, nhiệt, táo xâm nhập bì phu.", tay:"Tác nhân môi trường", tayD:"Tia UV là nguyên nhân lão hoá ngoại sinh lớn nhất.", act:"Chống nắng hằng ngày.", s:["hughes"] },
  { dong:"Khí trệ huyết ứ", dongD:"Khí huyết không lưu thông.", tay:"Ứ dịch, phù", tayD:"Dẫn lưu bạch huyết kém.", act:"Dẫn lưu, vận động, kê cao đầu khi ngủ.", s:[] }
],
ingredients: [
  { img:"i_rauma", t:"Rau má", e:"mid", dy:"Thanh nhiệt, giải độc.", kh:"Madecassoside, asiaticoside kích thích nguyên bào sợi, tăng tổng hợp collagen, hỗ trợ lành thương (“cica” của K-beauty).", w:"Hiếm khi dị ứng; cây quen thuộc ở Việt Nam.", s:["centella"] },
  { img:"i_nghe", t:"Nghệ (curcumin)", e:"weak", dy:"Hoạt huyết, tiêu viêm.", kh:"Kháng viêm, chống oxy hoá trong phòng thí nghiệm và nghiên cứu nhỏ.", w:"Nhuộm vàng da và vải; có người bị kích ứng." },
  { img:"i_tra", t:"Trà xanh (EGCG)", e:"mid", dy:"Thanh nhiệt.", kh:"Chống oxy hoá, hỗ trợ bảo vệ khi ra nắng.", w:"Không thay được kem chống nắng." },
  { img:"i_sam", t:"Nhân sâm", e:"weak", dy:"Đại bổ nguyên khí.", kh:"Ginsenoside; vài nghiên cứu nhỏ về nếp nhăn; nền tảng hanbang Hàn Quốc.", w:"Bằng chứng còn hạn chế." },
  { img:"i_gao", t:"Gạo, cám gạo", e:"weak", dy:"Kinh nghiệm dân gian Việt Nam, Nhật Bản.", kh:"Acid ferulic, inositol: làm dịu, chống oxy hoá.", w:"Nước vo gạo để lâu dễ nhiễm khuẩn: dùng trong ngày." },
  { img:"i_bachchi", t:"Bạch chỉ", e:"trad", dy:"Trừ phong, “làm trắng” trong các bài mặt nạ cổ.", kh:"Thuộc họ Hoa tán, nhóm cây chứa furocoumarin gây viêm da khi gặp nắng.", w:"Không dùng ban ngày.", s:["dermnet"] },
  { img:"i_chanh", t:"Chanh", e:"trad", dy:"Mẹo dân gian trị thâm.", kh:"Nước cốt chanh dính da rồi ra nắng có thể gây viêm da quang độc, để lại vết thâm.", w:"Khuyên học viên tránh đắp chanh lên mặt.", s:["dermnet"] },
  { img:"i_retinoid", t:"Retinoid", e:"strong", dy:"—", kh:"Tretinoin có bằng chứng tốt nhất trong các hoạt chất bôi cho lão hoá do nắng.", w:"Thận trọng khi mang thai hoặc chuẩn bị mang thai; bắt đầu chậm.", s:["retinoid"] },
  { img:"i_spf", t:"Kem chống nắng", e:"strong", dy:"Tương ứng việc “tránh ngoại tà”.", kh:"Thử nghiệm 903 người: dùng SPF 15+ hằng ngày, lão hoá da ít hơn 24% sau 4,5 năm.", w:"Thoa đủ lượng, thoa lại khi ra ngoài lâu.", s:["hughes"] }
],

/* ---------------- PHƯƠNG PHÁP KHÁC ---------------- */
methods: [
  { img:"o_kobido", t:"Kobido", o:"Nhật Bản, 1472", d:"Massage nhịp nhanh chậm xen kẽ, hơn 40 kỹ thuật tay.", learn:"Cao", e:"trad", s:["kobido"] },
  { img:"n_guasha", t:"Gua sha mặt", o:"Trung Quốc", d:"Cạo nhẹ bằng đá theo hướng dẫn lưu. Bằng chứng gốc là gua sha mạnh trên lưng, không phải trên mặt.", learn:"Trung bình", e:"weak", s:["guasha"] },
  { img:"mld_6", t:"Dẫn lưu bạch huyết", o:"Pháp, 1932", d:"Lực rất nhẹ, nhịp tròn đều; dùng trong liệu pháp giảm phù, ít nghiên cứu cho thẩm mỹ.", learn:"Trung bình–cao", e:"mid", s:["vodder","abmp_mld"] },
  { img:"m_kansa", t:"Mukha Abhyanga, gậy Kansa", o:"Ấn Độ", d:"Massage mặt với dầu ấm và gậy hợp kim đồng, tác động điểm marma.", learn:"Trung bình", e:"trad", s:[] },
  { img:"m_dienchan", t:"Diện chẩn", o:"Việt Nam, đầu thập niên 1980", d:"Que dò, cây lăn trên huyệt và đồ hình phản chiếu.", learn:"Cao nếu dùng trị liệu", e:"trad", s:["dc_official","sggp"] },
  { img:"m_cupping", t:"Giác hơi mặt", o:"Đông Á", d:"Cốc silicon nhỏ di chuyển trên da.", learn:"Trung bình; tránh khi giãn mao mạch, dùng thuốc chống đông", e:"weak", s:[] },
  { img:"m_neck", t:"Thả lỏng mạc cổ vai", o:"Vật lý trị liệu", d:"Cơ ức đòn chũm, cơ thang, cơ dưới chẩm; liên quan tư thế đầu.", learn:"Gần với yoga phục hồi", e:"mid", s:[] },
  { img:"n_eye", t:"Yoga mắt, quy tắc 20-20-20", o:"Nhãn khoa và yoga", d:"Cứ 20 phút nhìn xa khoảng 6 m trong 20 giây; chớp mắt chủ động.", learn:"Thấp", e:"mid", s:["aao"] },
  { img:"c_us", t:"Thiết bị vi dòng, LED", o:"Công nghệ làm đẹp", d:"Phân khúc tăng nhanh; nên hiểu để tư vấn học viên.", learn:"Thấp nếu chỉ tư vấn", e:"weak", s:["accio"] },
  { img:"m_goidau", t:"Cạo gió, gội đầu dưỡng sinh", o:"Việt Nam", d:"Thói quen quen thuộc, cầu nối văn hoá khi giới thiệu chạm mặt, đầu, cổ.", learn:"Thấp–trung bình", e:"trad", s:[] }
],
methodsMore: [
  { t:"Massage trong miệng (buccal)", d:"Thả lỏng cơ mút, cơ cắn từ bên trong; cần găng tay, vệ sinh, đồng thuận rõ ràng." },
  { t:"Facial Reflexology (Sorensen, 1988)", d:"Kết hợp Diện chẩn với truyền thống Nam Mỹ và giải phẫu.", s:["sorensen"] },
  { t:"Chỉnh tư thế đầu", d:"Mô hình ước tính: cúi đầu 15° làm cổ chịu khoảng 12 kg, 45° khoảng 22 kg, 60° khoảng 27 kg.", s:["hansraj"] }
],

/* ---------------- SO SÁNH QUỐC GIA ---------------- */
countries: [
  { c:"Nhật Bản", img:"c_jp", short:"Tối giản, phòng ngừa, da “mochi”.", phil:"Tối giản, phòng ngừa; coi trọng chống nắng và làm sáng da (bihaku).",
    ritual:"4–6 bước: tẩy trang dầu và sữa rửa mặt, lotion vỗ nhiều lớp mỏng, tinh chất, kem, chống nắng.",
    ingr:"Cám gạo, men lên men, trà xanh, dầu hoa trà, tảo biển.", hand:"Kobido, Shiatsu, con lăn mặt, tập cơ biểu cảm (表情筋トレ).",
    trend:"Tập cơ mặt do chuyên gia lớn tuổi dẫn dắt.", lesson:"Nhịp chậm, nghi thức hoá, kỹ thuật tay chuẩn hoá.", s:["sokoglam","kobido","jp63"] },
  { c:"Hàn Quốc", img:"c_kr", short:"Nhiều lớp, “glass skin”, nay là “slow aging”.", phil:"Cấp ẩm nhiều lớp; từ 2024 chuyển sang “slow aging” và “skip-care” (cắt bớt bước).",
    ritual:"Có thể tới 10 bước: dầu, sữa rửa, tẩy tế bào chết, toner, essence, serum, mặt nạ giấy, kem mắt, kem dưỡng, chống nắng.",
    ingr:"Rau má (cica), nhân sâm (hanbang), dịch ốc sên, ngải cứu, lên men.", hand:"Thiết bị tại nhà (vi dòng, RF, LED), da liễu thẩm mỹ phổ biến.",
    trend:"Olive Young: nhóm slow aging tăng hơn 60% năm 2024.", lesson:"Đặt face yoga trong câu chuyện lối sống “slow aging”.", s:["sokoglam","oliveyoung","skipcare"] },
  { c:"Trung Quốc", img:"c_cn", short:"Đông y: đẹp từ khí huyết, tạng phủ.", phil:"Vẻ đẹp phản ánh khí huyết và tạng phủ; dưỡng sinh từ trong ra ngoài.",
    ritual:"Thực dưỡng, trà thảo mộc; mặt nạ thảo dược.", ingr:"Bột trân châu, nhân sâm, bạch chỉ (gây cảm quang), đương quy, cam thảo, câu kỷ.",
    hand:"Quát sa (gua sha), con lăn ngọc, giác hơi mặt, châm cứu thẩm mỹ, Tui Na.", trend:"Gua sha toàn cầu hoá qua mạng xã hội.",
    lesson:"Kể chuyện kinh lạc hấp dẫn nhưng nói rõ mức bằng chứng.", s:["lk49","guasha"] },
  { c:"Việt Nam", img:"c_vn", short:"Đông y, dân gian và K-beauty đan xen.", phil:"Đan xen Đông y, kinh nghiệm dân gian và ảnh hưởng mạnh của K-beauty; chuộng da sáng, “thiên nhiên”.",
    ritual:"Dân gian: nước vo gạo, nghệ mật ong, xông lá; hiện đại: routine kiểu Hàn.", ingr:"Rau má, nghệ, gạo, trà xanh, lô hội.",
    hand:"Diện chẩn, bấm huyệt dưỡng sinh, cạo gió, gội đầu dưỡng sinh.", trend:"Cơ sở thẩm mỹ tăng từ khoảng 100 (2000) lên 5.000 (2020).",
    lesson:"Cạo gió, gội đầu dưỡng sinh là thói quen sẵn có: cầu nối cho face yoga và cổ vai gáy.", s:["dbnd","lc_dc"] },
  { c:"Ấn Độ", img:"c_in", short:"Ayurveda: dầu ấm, marma.", phil:"Cân bằng ba dosha; da phản ánh tiêu hoá (agni).",
    ritual:"Ubtan (bột đậu, nghệ, đàn hương), dầu mặt, Mukha Abhyanga.", ingr:"Nghệ, đàn hương, neem, nghệ tây, ghee.",
    hand:"Gậy Kansa, huyệt Marma; Simhasana từ Hatha yoga.", trend:"Ayurveda cao cấp xuất khẩu.", lesson:"Cùng gốc yoga: dễ ghép pranayama, dầu ấm, marma.", s:["hyp"] },
  { c:"Thái Lan", img:"c_th", short:"Nhiệt, thảo dược, áp lực.", phil:"Y học cổ truyền Thái: nhiệt, thảo dược, áp lực.",
    ritual:"Túi chườm thảo dược nóng, massage mặt Thái.", ingr:"Me, nghệ, sả, gừng, dừa.", hand:"Nuad Thai (UNESCO ghi danh năm 2019).",
    trend:"Du lịch wellness, spa nghỉ dưỡng.", lesson:"Thêm nhiệt ấm và thảo dược vào phần thư giãn.", s:["unesco_nuad"] },
  { c:"Pháp", img:"c_fr", short:"Ít mà chất, dược mỹ phẩm.", phil:"Da khoẻ, dược mỹ phẩm bán ở hiệu thuốc.",
    ritual:"Làm sạch nhẹ (nước micellar), serum, kem.", ingr:"Nước khoáng suối nóng, polyphenol nho.", hand:"Véo lăn Jacquet, dẫn lưu Vodder (Cannes, 1932).",
    trend:"Thẩm mỹ tự nhiên.", lesson:"Chuẩn hoá kỹ thuật dẫn lưu, dùng ngôn ngữ chính xác.", s:["vodder"] },
  { c:"Anh / Mỹ", img:"c_us", short:"Hoạt chất có bằng chứng, app, chứng chỉ.", phil:"Dựa trên bằng chứng: retinoid, chống nắng; face fitness thành ngành dịch vụ.",
    ritual:"Làm sạch, vitamin C, retinoid, kem dưỡng, chống nắng.", ingr:"Retinoid, vitamin C, niacinamide, peptide, ceramide.",
    hand:"Face yoga (Hagen, Collins), thiết bị vi dòng, LED.", trend:"App face yoga, chứng chỉ online.", lesson:"Học mô hình kinh doanh: app, khoá online, chứng chỉ.", s:["hagen","collins","apps"] },
  { c:"Brazil", img:"c_br", short:"Âm ngữ trị liệu làm thẩm mỹ.", phil:"Fonoaudiologia estética: chuyên viên âm ngữ trị liệu dùng bài tập cơ mặt cho thẩm mỹ.",
    ritual:"Đánh giá cơ mặt–cổ, bài tập, massage.", ingr:"—", hand:"Bài tập vận động miệng–mặt.",
    trend:"Cả 9 nghiên cứu trong tổng quan 2014 đều từ Nam Mỹ.", lesson:"Mô hình “phục hồi chức năng sang thẩm mỹ” rất gần yoga phục hồi.", s:["brazil","vanborsel"] }
],

/* ---------------- NGUỒN ---------------- */
sources: {
  alam:{ t:"Alam M. và cs. Association of Facial Exercise With the Appearance of Aging. JAMA Dermatology, 2018 (27 người tham gia, 16 hoàn thành). Thông cáo Northwestern University.", u:"https://news.northwestern.edu/stories/2018/january/facial-exercises-help-middle-aged-women-appear-more-youthful" },
  sd2018:{ t:"ScienceDaily (2018). Facial exercises help middle-aged women appear more youthful (Gary Sikorski thiết kế 32 bài, là đồng tác giả).", u:"https://www.sciencedaily.com/releases/2018/01/180103160142.htm" },
  vanborsel:{ t:"Van Borsel J. và cs. The effectiveness of facial exercises for facial rejuvenation: a systematic review. Aesthetic Surgery Journal 34(1):22–27, 2014. Tóm tắt trên MedEsthetics.", u:"https://www.medestheticsmag.com/news/article/21145684/benefits-of-facial-exercises-for-aesthetic-rejuvenation-inconclusive" },
  scielo:{ t:"de Manincor E.O. và cs. Facial exercises for rejuvenation: A systematic review. Revista CEFAC 26(6), 2024 (7 nghiên cứu).", u:"https://www.scielo.br/j/rcefac/a/QJYZ8mZXHD7krKHxGzhsJGz/?format=html&lang=en" },
  guzel:{ t:"Güzel và cs. Effect of Intensive Face Yoga on Facial Muscles Tonus, Stiffness, and Elasticity in Middle-Aged Women. Medicina (Kaunas), 2025.", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC12112979/" },
  hwang:{ t:"Hwang U.J. và cs. Effect of a Facial Muscle Exercise Device on Facial Rejuvenation. Aesthetic Surgery Journal, 2018 (50 phụ nữ, dụng cụ PAO của Nhật).", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC5888959/" },
  nct:{ t:"ClinicalTrials.gov NCT06765408. Effect of Face Yoga on Mimic Muscles.", u:"https://clinicaltrials.gov/study/NCT06765408" },
  hagen:{ t:"Penguin Random House. The Yoga Face – Annelise Hagen (2007).", u:"https://www.penguinrandomhouse.com/books/300700/the-yoga-face-by-annelise-hagen/" },
  nbc:{ t:"NBC News. New Yorkers try facial yoga for natural lift.", u:"https://www.nbcnews.com/id/wbna20610259" },
  takatsu:{ t:"Discover Nikkei (2026). Fumiko Takatsu.", u:"https://discovernikkei.org/en/journal/2026/1/7/fumiko-takatsu/" },
  facercise:{ t:"Maggio C., Roderick K. Facercise: The Dynamic Muscle-Toning Program for Renewed Vitality and a More Youthful Appearance (1995). Goodreads.", u:"https://www.goodreads.com/book/show/255397.Facercise" },
  ctv:{ t:"CTV News. Does face yoga actually work? Experts weigh in.", u:"https://www.ctvnews.ca/health/article/does-face-yoga-actually-work-experts-weigh-in-on-its-slimming-anti-aging-effects/" },
  collins:{ t:"Evolve Beauty. Face Yoga Exercises From Danielle Collins (tiểu sử, các văn bằng).", u:"https://www.evolvebeauty.com/blogs/news/face-yoga-exercises-from-danielle-collins" },
  sikorski:{ t:"AARP. Face Workouts That Work (Gary Sikorski, Happy Face Yoga).", u:"https://www.aarp.org/health/healthy-living/info-2018/facial-exercises-fd.html" },
  gvr:{ t:"Treendly, dẫn số liệu Grand View Research: face yoga 779,5 triệu USD (2020), 1,02 tỷ USD (2027), tăng 5,3%/năm.", u:"https://treendly.com/blog/face-yoga-the-emerging-trend-for-natural-anti-aging-and-facial-toning" },
  accio:{ t:"Accio. Face yoga equipment: tăng 14,1%/năm giai đoạn 2026–2033 (tổng hợp thương mại).", u:"https://www.accio.com/business/face-yoga-equipment" },
  gwi:{ t:"Global Wellness Institute (2024). The Global Wellness Economy Reaches a New Peak of $6.3 Trillion.", u:"https://globalwellnessinstitute.org/press-room/press-releases/the-global-wellness-economy-reaches-a-new-peak-of-6-3-trillion-and-is-forecast-to-hit-9-trillion-by-2028/" },
  apps:{ t:"ScreensDesign. Guided face yoga apps (ước tính doanh thu và lượt cài trung bình).", u:"https://screensdesign.com/categories/guided-face-yoga-apps/" },
  cosbiz:{ t:"Cosmetics Business. How can beauty brands benefit from the face yoga trend?", u:"https://cosmeticsbusiness.com/how-can-beauty-brands-benefit-from-the-face-yoga-trend--138695" },
  dbnd:{ t:"Báo Đại biểu Nhân dân. Nhận diện và nắm bắt cơ hội tăng trưởng đột phá thị trường làm đẹp tại Việt Nam.", u:"https://daibieunhandan.vn/nhan-dien-va-nam-bat-co-hoi-tang-truong-dot-pha-thi-truong-lam-dep-tai-viet-nam-10335369.html" },
  bcompany:{ t:"B-Company. Vietnam Beauty Market 2025: Key Updates, Investment Activities, and Trends.", u:"https://b-company.jp/vietnam-beauty-market-2025-key-updates-investment-activities-and-trends/" },
  ken:{ t:"Ken Research. Vietnam Fitness Services Market (37,5% người dân tập thể thao thường xuyên năm 2024; khoảng 600 phòng tập có tổ chức năm 2023; thị trường khoảng 492 triệu USD năm 2025).", u:"https://www.kenresearch.com/industry-reports/vietnam-fitness-services-market.md" },
  plo:{ t:"PLO. Hơn 3.000 thương hiệu ngành làm đẹp quy tụ tại triển lãm ở TP.HCM.", u:"https://plo.vn/hon-3000-thuong-hieu-nganh-lam-dep-dang-quy-tu-tai-trien-lam-o-tphcm-post862101.html" },
  unica:{ t:"Unica. Yoga trẻ hoá và làm đẹp cho khuôn mặt (Nguyễn Hiếu).", u:"https://unica.vn/yoga-tre-hoa-va-lam-dep-cho-khuon-mat" },
  athas:{ t:"Athas Saigon. Yoga khuôn mặt: “Dùng đi, không là mất đó” (workshop 28/5/2022).", u:"https://www.athassaigon.com/events/2022/5/28/yoga-khun-mt-dng-i-khng-l-mt-face-yoga-workshop-use-them-or-lose-them" },
  udemy:{ t:"Udemy. 28 ngày điêu khắc gương mặt rạng ngời cùng yoga face.", u:"https://www.udemy.com/course/yoga-face-coach-trang/" },
  vinmec:{ t:"Vinmec. Các bài tập trên mặt có thực sự giúp bạn trông trẻ hơn?", u:"https://www.vinmec.com/vie/bai-viet/cac-bai-tap-tren-mat-co-thuc-su-giup-ban-trong-tre-hon-vi" },
  lc_fy:{ t:"Nhà thuốc Long Châu. Face yoga: bí quyết cho làn da săn chắc.", u:"https://nhathuoclongchau.com.vn/bai-viet/face-yoga-bi-quyet-cho-lan-da-san-chac-tre-dep.html" },
  ytl:{ t:"Yoga Therapy Vietnam. Đào tạo Yoga Trị liệu 200 giờ.", u:"https://yogatherapy.vn/dao-tao-yoga-tri-lieu/" },
  omf:{ t:"OM Factory Vietnam. Khoá đào tạo giáo viên Yin Yoga.", u:"https://omfactory.vn/khoa-dao-tao-giao-vien-yin-yoga/" },
  ydaily:{ t:"Yogadaily. Khoá đào tạo giáo viên Yoga trị liệu online.", u:"https://yogaonline.yogadaily.com.vn/san-pham/khoa-hoc-huan-luyen-vien-yoga-tri-lieu-v2" },
  lc_dc:{ t:"Nhà thuốc Long Châu. Diện chẩn chữa mất ngủ có hiệu quả không? (ra đời đầu thập niên 1980; chưa được chứng minh khoa học).", u:"https://nhathuoclongchau.com.vn/bai-viet/dien-chan-chua-mat-ngu-co-hieu-qua-khong.html" },
  eco_dc:{ t:"Ecopharma. Diện chẩn chữa mất ngủ (các bộ huyệt 26; 124–34–0; 1–26–37–50–103–106–267–300).", u:"https://ecopharma.com.vn/dien-chan-chua-mat-ngu/" },
  lc_dc2:{ t:"Nhà thuốc Long Châu. Chữa rối loạn tiêu hoá bằng diện chẩn: công dụng và lưu ý.", u:"https://nhathuoclongchau.com.vn/bai-viet/chua-roi-loan-tieu-hoa-bang-dien-chan-cong-dung-va-nhung-dieu-can-luu-y-54331.html" },
  dc_official:{ t:"Việt Y Đạo (trang của GS.TSKH Bùi Quốc Châu). Các huyệt trên mặt Diện Chẩn: hệ trục định vị, huyệt 19, 26.", u:"https://dienchan.com/cac-huyet-tren-mat-dien-chan" },
  dc_map:{ t:"Diện Chẩn Việt. Đồ hình phản chiếu nội tạng (trích “Thực hành Diện Chẩn – Điều khiển liệu pháp”, GS.TS Bùi Quốc Châu).", u:"https://www.dienchanviet.com/gstskh-bui-quoc-chau/do-hinh-phan-chieu-noi-tang" },
  dc_4:{ t:"Thầy thuốc tự thân. Tứ đại huyệt Diện Chẩn (26, 19, 127, 0: vị trí và công dụng theo tài liệu).", u:"https://thaythuoctuthan.vn/blog/tu-dai-huyet-dien-chan" },
  dc_sinh:{ t:"Dụng cụ Diện Chẩn. Sinh huyệt và định huyệt Diện Chẩn là gì? (26 huyệt mốc, số huyệt 0–555, cách dò sinh huyệt).", u:"https://dungcudienchan.vn/sinh-huyet-dinh-huyet-dien-chan-la-gi/" },
  dc_spine:{ t:"Thiết bị Diện Chẩn. Đồ hình phản chiếu trên khuôn mặt (sống mũi là trục phản chiếu cột sống).", u:"https://thietbidienchan.com/do-hinh-phan-chieu-tren-khuon-mat-trong-dien-chan-va-ung-dung-nhan-dien-suc-khoe/" },
  sggp:{ t:"SGGP (13/4/2012). Sở Y tế TP.HCM yêu cầu ông Bùi Quốc Châu cung cấp đủ chứng cứ khoa học cho Bộ Y tế và không dùng, quảng bá Diện chẩn để chữa bệnh khi chưa được phép.", u:"https://www.sggp.org.vn/phan-hoi-tu-bai-viet-mo-ho-lieu-phap-dien-chan-se-xu-ly-viec-kham-chua-benh-trai-phep-130463.html" },
  sorensen:{ t:"ABMP. Lone Sorensen – Facial Reflexology.", u:"https://learn.abmp.com/node/15401" },
  eminence:{ t:"Eminence Organics. Facial Reflexology (Dien Chan và Sorensensistem).", u:"https://eminenceorganics.com/us/blog/skin-care/facial-reflexology-benefits-reflexology-may-surprise-you.html" },
  lk49:{ t:"Hoàng Đế Nội Kinh – Linh Khu, thiên 49 “Ngũ sắc” (五色). Chinese Text Project.", u:"https://ctext.org/huangdi-neijing/wu-se" },
  lk4:{ t:"Hoàng Đế Nội Kinh – Linh Khu, thiên 4 “Tà khí tạng phủ bệnh hình” (邪氣藏府病形).", u:"https://ctext.org/huangdi-neijing/xie-qi-zang-fu-bing-xing" },
  lk10:{ t:"Hoàng Đế Nội Kinh – Linh Khu, thiên 10 “Kinh mạch” (經脈).", u:"https://ctext.org/huangdi-neijing/jing-mai" },
  sv1:{ t:"Hoàng Đế Nội Kinh – Tố Vấn, thiên 1 “Thượng cổ thiên chân luận” (上古天真論).", u:"https://ctext.org/huangdi-neijing/shang-gu-tian-zhen-lun" },
  sv9:{ t:"Hoàng Đế Nội Kinh – Tố Vấn, thiên 9 “Lục tiết tạng tượng luận” (六節藏象論).", u:"https://ctext.org/huangdi-neijing/liu-jie-zang-xiang-lun" },
  nanjing:{ t:"Nạn Kinh, nạn 61: “Vọng nhi tri chi vị chi thần” (望而知之謂之神).", u:"" },
  hyp:{ t:"Hatha Yoga Pradipika (Svatmarama, TK 15), chương 1: Simhasana.", u:"" },
  statpearls:{ t:"StatPearls. Anatomy, Head and Neck, Lymph Nodes.", u:"https://www.statpearls.com/point-of-care/25607" },
  kenhub:{ t:"Kenhub. Facial lymph nodes.", u:"https://www.kenhub.com/en/library/anatomy/facial-lymph-nodes" },
  vodder:{ t:"Wittlinger H. và cs. Dr. Vodder's Manual Lymph Drainage. Thieme.", u:"https://shop.thieme.de/en/Dr.-Vodder-s-Manual-Lymph-Drainage/9783132578746" },
  abmp_mld:{ t:"ABMP. Manual Lymph Drainage (lực dưới khoảng 9 ounce/inch², nhịp tròn đều).", u:"https://plove.abmp.com/manual-lymph-drainage" },
  guasha:{ t:"North Biomedical. Gua Sha Benefits for Skin: What the Science Actually Supports (bình luận nghiên cứu Nielsen 2007).", u:"https://northbiomedical.com/articles/gua-sha-benefits/" },
  kobido:{ t:"Dermascope. Keeping Up with Kobido: History, Benefits, Incorporation.", u:"https://www.dermascope.com/keeping-up-with-kobido-history-benefits-incorporation/" },
  sokoglam:{ t:"Soko Glam – The Klog. Korean vs. Japanese Skin Care.", u:"https://sokoglam.com/blogs/theklog/korean-skin-care-vs-japanese-skin-care" },
  oliveyoung:{ t:"CJ Newsroom. CJ Olive Young reports over 60% annual sales growth in slow-aging products.", u:"https://newsroom.cj.net/cj-olive-young-reports-over-60-annual-sales-growth-in-slow-aging-products" },
  skipcare:{ t:"Harper's Bazaar Singapore. Skip-care, the K-beauty trend.", u:"https://www.harpersbazaar.com.sg/gallery/skip-care-k-beauty-trend/" },
  jp63:{ t:"The Standard (HK). 63-year-old beauty expert's facial muscle training.", u:"https://www.thestandard.com.hk/wellness/article/324944/63-yo-beauty-experts-secret-to-reversing-skin-age-by-10-years-without-surgery" },
  brazil:{ t:"Speech Therapy and Facial Esthetic: Experience of Brazil in Primary Health Care. Revista Chilena de Fonoaudiología.", u:"https://revistaschilenas.uchile.cl/handle/2250/31977?show=full" },
  unesco_nuad:{ t:"UNESCO. Nuad Thai, traditional Thai massage (ghi danh năm 2019).", u:"https://ich.unesco.org/en/RL/nuad-thai-traditional-thai-massage-01384" },
  tcr:{ t:"Singh G.P., Chowdhury T., Bindu B., Schaller B. Sudden Infant Death Syndrome – Role of Trigeminocardiac Reflex: A Review. Frontiers in Neurology 7:221, 2016 (phản xạ lặn là một dạng phản xạ tam thoa–tim).", u:"https://www.frontiersin.org/journals/neurology/articles/10.3389/fneur.2016.00221/full" },
  coles:{ t:"Coles N.A. và cs. (2019), Psychological Bulletin: phân tích gộp 138 nghiên cứu về phản hồi nét mặt. Tin ScienceDaily.", u:"https://www.sciencedaily.com/releases/2019/04/190412094728.htm" },
  botox:{ t:"Wollmer M.A., Magid M., Kruger T.H.C., Finzi E. Treatment of Depression with Botulinum Toxin. Toxins 14(6):383, 2022 (tổng quan, gồm thử nghiệm Wollmer 2012, n = 30).", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9231293/" },
  loken:{ t:"Löken L.S. và cs. Coding of pleasant touch by unmyelinated afferents in humans. Nature Neuroscience 12:547–548, 2009.", u:"https://www.nature.com/articles/nn.2312" },
  penfield:{ t:"Penfield W., Boldrey E. Somatic motor and sensory representation in the cerebral cortex of man. Brain, 1937.", u:"" },
  aha:{ t:"American Heart Association. Warning Signs of a Heart Attack (đau lan hàm, cổ, cánh tay).", u:"https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack" },
  myers:{ t:"Myers T. Anatomy Trains (mô hình các đường mạc nối dài; Deep Front Line nối lưỡi, xương móng, cơ hoành, sàn chậu).", u:"" },
  hughes:{ t:"Hughes M.C. và cs. Sunscreen and prevention of skin aging: a randomized trial. Annals of Internal Medicine 158:781–790, 2013 (903 người, lão hoá ít hơn 24%).", u:"https://www.acpjournals.org/doi/10.7326/0003-4819-158-11-201306040-00002" },
  aad:{ t:"American Academy of Dermatology. Skin care during menopause (mất khoảng 30% collagen trong 5 năm đầu, sau đó khoảng 2% mỗi năm).", u:"https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/skin-care-during-menopause" },
  centella:{ t:"Bylka W. và cs. Centella asiatica in cosmetology. Postępy Dermatologii i Alergologii, 2013.", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/" },
  retinoid:{ t:"Mukherjee S. và cs. Retinoids in the treatment of skin aging: an overview of clinical efficacy and safety. Clinical Interventions in Aging, 2006.", u:"https://pmc.ncbi.nlm.nih.gov/articles/PMC2699641/" },
  dermnet:{ t:"DermNet. Phytophotodermatitis (viêm da quang độc do nước chanh và cây họ Hoa tán).", u:"https://dermnetnz.org/topics/phytophotodermatitis" },
  aao:{ t:"American Academy of Ophthalmology. Computers, Digital Devices and Eye Strain (quy tắc 20-20-20).", u:"https://www.aao.org/eye-health/tips-prevention/computer-usage" },
  hansraj:{ t:"Hansraj K.K. Assessment of stresses in the cervical spine caused by posture and position of the head. Surgical Technology International 25:277–279, 2014. Tin NPR.", u:"https://www.npr.org/sections/thetwo-way/2014/11/20/365473750/keep-your-head-up-text-neck-can-take-a-toll-on-the-spine" },
  luat:{ t:"Luật Khám bệnh, chữa bệnh số 15/2023/QH15 (hiệu lực từ 01/01/2024).", u:"" }
}
};
